//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPLauncherNET.Languages {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de_DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAMPLauncherNET.Languages.de-DE", typeof(de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über ähnelt.
        /// </summary>
        internal static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SAMPLauncher NET ist ein Launcher für San Andreas Multiplayer.
        ///
        ///Diese Software bleibt für immer kostenlos und ist mit GPLv3 lizenziert.
        ///
        ///Das Projekt befindet sich auf ähnelt.
        /// </summary>
        internal static string ABOUT_DESCRIPTION {
            get {
                return ResourceManager.GetString("ABOUT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue API hinzufügen ähnelt.
        /// </summary>
        internal static string ADD_NEW_API {
            get {
                return ResourceManager.GetString("ADD_NEW_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favorit hinzufügen ähnelt.
        /// </summary>
        internal static string ADD_SERVER_TO_FAVOURITES {
            get {
                return ResourceManager.GetString("ADD_SERVER_TO_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bereits in den Favoriten ähnelt.
        /// </summary>
        internal static string ALREADY_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("ALREADY_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API ähnelt.
        /// </summary>
        internal static string API {
            get {
                return ResourceManager.GetString("API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API Zugriffspunkt ähnelt.
        /// </summary>
        internal static string API_ENDPOINT {
            get {
                return ResourceManager.GetString("API_ENDPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte füge einen validen API Zugriffspunkt hinzu. ähnelt.
        /// </summary>
        internal static string API_ENDPOINT_MISSING {
            get {
                return ResourceManager.GetString("API_ENDPOINT_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API Zugriffspunkt fehlt ähnelt.
        /// </summary>
        internal static string API_ENDPOINT_MISSING_TITLE {
            get {
                return ResourceManager.GetString("API_ENDPOINT_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API Name ähnelt.
        /// </summary>
        internal static string API_NAME {
            get {
                return ResourceManager.GetString("API_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte füge einen API Namen hinzu ähnelt.
        /// </summary>
        internal static string API_NAME_MISSING {
            get {
                return ResourceManager.GetString("API_NAME_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API Name fehlt ähnelt.
        /// </summary>
        internal static string API_NAME_MISSING_TITLE {
            get {
                return ResourceManager.GetString("API_NAME_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API Typ ähnelt.
        /// </summary>
        internal static string API_TYPE {
            get {
                return ResourceManager.GetString("API_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte selektiere einen API Typ ähnelt.
        /// </summary>
        internal static string API_TYPE_MISSING {
            get {
                return ResourceManager.GetString("API_TYPE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API Typ fehlt ähnelt.
        /// </summary>
        internal static string API_TYPE_MISSING_TITLE {
            get {
                return ResourceManager.GetString("API_TYPE_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audio Benachrichtigungen ausblenden ähnelt.
        /// </summary>
        internal static string AUDIO_MESSAGE_OFF {
            get {
                return ResourceManager.GetString("AUDIO_MESSAGE_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audio Proxy nicht verwenden ähnelt.
        /// </summary>
        internal static string AUDIO_PROXY_OFF {
            get {
                return ResourceManager.GetString("AUDIO_PROXY_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schließen, wenn ausgeführt ähnelt.
        /// </summary>
        internal static string CLOSE_WHEN_LAUNCHED {
            get {
                return ResourceManager.GetString("CLOSE_WHEN_LAUNCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbinden ähnelt.
        /// </summary>
        internal static string CONNECT {
            get {
                return ResourceManager.GetString("CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jetzt verbinden! ähnelt.
        /// </summary>
        internal static string CONNECT_NOW {
            get {
                return ResourceManager.GetString("CONNECT_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Verbinden ähnelt.
        /// </summary>
        internal static string CONNECT_TITLE {
            get {
                return ResourceManager.GetString("CONNECT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbinde mit RCON ähnelt.
        /// </summary>
        internal static string CONNECT_WITH_RCON {
            get {
                return ResourceManager.GetString("CONNECT_WITH_RCON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debug Modus ähnelt.
        /// </summary>
        internal static string DEBUG_MODE {
            get {
                return ResourceManager.GetString("DEBUG_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchetst du wirklich die ausgewählten Bilder unwideruflich löschen? ähnelt.
        /// </summary>
        internal static string DELETE_SELECTED_IMAGES {
            get {
                return ResourceManager.GetString("DELETE_SELECTED_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgewälte Bilder löschen ähnelt.
        /// </summary>
        internal static string DELETE_SELECTED_IMAGES_TITLE {
            get {
                return ResourceManager.GetString("DELETE_SELECTED_IMAGES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Direkter Textdraw zu Bildschirm Render Methode (langsam) ähnelt.
        /// </summary>
        internal static string DIRECT_MODE {
            get {
                return ResourceManager.GetString("DIRECT_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kopfbewegungen abschalten ähnelt.
        /// </summary>
        internal static string DISABLE_HEAD_MOVE {
            get {
                return ResourceManager.GetString("DISABLE_HEAD_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holländisch (Nederlands) ähnelt.
        /// </summary>
        internal static string DUTCH {
            get {
                return ResourceManager.GetString("DUTCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - API bearbeiten ähnelt.
        /// </summary>
        internal static string EDIT_API_TITLE {
            get {
                return ResourceManager.GetString("EDIT_API_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selektierte API bearbeiten ähnelt.
        /// </summary>
        internal static string EDIT_SELECTED_API {
            get {
                return ResourceManager.GetString("EDIT_SELECTED_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Englisch (English) ähnelt.
        /// </summary>
        internal static string ENGLISH {
            get {
                return ResourceManager.GetString("ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Erweiterte Server Informationen ähnelt.
        /// </summary>
        internal static string EXTENDED_SERVER_INFORMATION_TITLE {
            get {
                return ResourceManager.GetString("EXTENDED_SERVER_INFORMATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte selektiere eine Favoritenliste ähnelt.
        /// </summary>
        internal static string FAVOURITE_LIST_NOT_SELECTED {
            get {
                return ResourceManager.GetString("FAVOURITE_LIST_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favoritenliste nicht selektiert ähnelt.
        /// </summary>
        internal static string FAVOURITE_LIST_NOT_SELECTED_TITLE {
            get {
                return ResourceManager.GetString("FAVOURITE_LIST_NOT_SELECTED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filtere Hostname ähnelt.
        /// </summary>
        internal static string FILTER_HOSTNAME {
            get {
                return ResourceManager.GetString("FILTER_HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filtere IP und Port ähnelt.
        /// </summary>
        internal static string FILTER_IP_AND_PORT {
            get {
                return ResourceManager.GetString("FILTER_IP_AND_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filtere Sprache ähnelt.
        /// </summary>
        internal static string FILTER_LANGUAGE {
            get {
                return ResourceManager.GetString("FILTER_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filtere Modus ähnelt.
        /// </summary>
        internal static string FILTER_MODE {
            get {
                return ResourceManager.GetString("FILTER_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schriftart ähnelt.
        /// </summary>
        internal static string FONT_FACE {
            get {
                return ResourceManager.GetString("FONT_FACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schriftstärke ähnelt.
        /// </summary>
        internal static string FONT_WEIGHT {
            get {
                return ResourceManager.GetString("FONT_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FPS Limit ähnelt.
        /// </summary>
        internal static string FPS_LIMIT {
            get {
                return ResourceManager.GetString("FPS_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gallerie ähnelt.
        /// </summary>
        internal static string GALLERY {
            get {
                return ResourceManager.GetString("GALLERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spielmodus ähnelt.
        /// </summary>
        internal static string GAMEMODE {
            get {
                return ResourceManager.GetString("GAMEMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Georgisch (ქართული) ähnelt.
        /// </summary>
        internal static string GEORGIAN {
            get {
                return ResourceManager.GetString("GEORGIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutsch ähnelt.
        /// </summary>
        internal static string GERMAN {
            get {
                return ResourceManager.GetString("GERMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GitHub Projekt SAMPLauncherNET ähnelt.
        /// </summary>
        internal static string GITHUB_PROJECT {
            get {
                return ResourceManager.GetString("GITHUB_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hostname ähnelt.
        /// </summary>
        internal static string HOSTNAME {
            get {
                return ResourceManager.GetString("HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IME (Input Method Editor) freischalten ähnelt.
        /// </summary>
        internal static string IME {
            get {
                return ResourceManager.GetString("IME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eingabefehler ähnelt.
        /// </summary>
        internal static string INPUT_ERROR {
            get {
                return ResourceManager.GetString("INPUT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Füge einen Filter hier ein... ähnelt.
        /// </summary>
        internal static string INSERT_FILTER_HERE {
            get {
                return ResourceManager.GetString("INSERT_FILTER_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Füge den RCON Passwort hier ein... ähnelt.
        /// </summary>
        internal static string INSERT_RCON_PASSWORD_HERE {
            get {
                return ResourceManager.GetString("INSERT_RCON_PASSWORD_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Füge den Server Passwort hier ein... ähnelt.
        /// </summary>
        internal static string INSERT_SERVER_PASSWORD_HERE {
            get {
                return ResourceManager.GetString("INSERT_SERVER_PASSWORD_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Füge einen Benutzernamen hier ein... ähnelt.
        /// </summary>
        internal static string INSERT_USERNAME_HERE {
            get {
                return ResourceManager.GetString("INSERT_USERNAME_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP und Port ähnelt.
        /// </summary>
        internal static string IP_AND_PORT {
            get {
                return ResourceManager.GetString("IP_AND_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Letzter Chatprotokoll ähnelt.
        /// </summary>
        internal static string LAST_CHATLOG {
            get {
                return ResourceManager.GetString("LAST_CHATLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debug Modus starten ähnelt.
        /// </summary>
        internal static string LAUNCH_DEBUG_MODE {
            get {
                return ResourceManager.GetString("LAUNCH_DEBUG_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Singleplayer starten ähnelt.
        /// </summary>
        internal static string LAUNCH_SINGLEPLAYER {
            get {
                return ResourceManager.GetString("LAUNCH_SINGLEPLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Launcher ähnelt.
        /// </summary>
        internal static string LAUNCHER_TITLE {
            get {
                return ResourceManager.GetString("LAUNCHER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multi Core ähnelt.
        /// </summary>
        internal static string MULTI_CORE {
            get {
                return ResourceManager.GetString("MULTI_CORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brauchst du Hilfe? Trete in den SA:MP Foren ein... ähnelt.
        /// </summary>
        internal static string NEED_HELP_FORUMS {
            get {
                return ResourceManager.GetString("NEED_HELP_FORUMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - API hinzuifügen ähnelt.
        /// </summary>
        internal static string NEW_API_TITLE {
            get {
                return ResourceManager.GetString("NEW_API_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keinen Chatprotokoll gefunden... ähnelt.
        /// </summary>
        internal static string NO_CHATLOG_FOUND {
            get {
                return ResourceManager.GetString("NO_CHATLOG_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es existieren keine Favoritenlisten. Um eine neue Favoritenliste zu erstellen, gehe zum &quot;API&quot; Tab, und erstelle eine neue Favoritenliste, oder stelle die Standarteintrage wieder her. ähnelt.
        /// </summary>
        internal static string NO_FAVOURITES {
            get {
                return ResourceManager.GetString("NO_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Favoritenlisten ähnelt.
        /// </summary>
        internal static string NO_FAVOURITES_TITLE {
            get {
                return ResourceManager.GetString("NO_FAVOURITES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein Namensschildstatus ähnelt.
        /// </summary>
        internal static string NO_NAMETAG_STATUS {
            get {
                return ResourceManager.GetString("NO_NAMETAG_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht in den Favoriten ähnelt.
        /// </summary>
        internal static string NOT_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("NOT_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optionen ähnelt.
        /// </summary>
        internal static string OPTIONS {
            get {
                return ResourceManager.GetString("OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Optionen ähnelt.
        /// </summary>
        internal static string OPTIONS_TITLE {
            get {
                return ResourceManager.GetString("OPTIONS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seitengröße ähnelt.
        /// </summary>
        internal static string PAGE_SIZE {
            get {
                return ResourceManager.GetString("PAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verzögerung ähnelt.
        /// </summary>
        internal static string PING {
            get {
                return ResourceManager.GetString("PING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spieler ähnelt.
        /// </summary>
        internal static string PLAYERS {
            get {
                return ResourceManager.GetString("PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte gebe einen Benutzernamen ein. ähnelt.
        /// </summary>
        internal static string PLEASE_TYPE_IN_USERNAME {
            get {
                return ResourceManager.GetString("PLEASE_TYPE_IN_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RCON Passwort ähnelt.
        /// </summary>
        internal static string RCON_PASSWORD {
            get {
                return ResourceManager.GetString("RCON_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - RCON Passwort ähnelt.
        /// </summary>
        internal static string RCON_PASSWORD_TITLE {
            get {
                return ResourceManager.GetString("RCON_PASSWORD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchtest du wirklich die selektierte APIs unwideruflich löschen? ähnelt.
        /// </summary>
        internal static string REMOVE_API {
            get {
                return ResourceManager.GetString("REMOVE_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selektierte API löschen ähnelt.
        /// </summary>
        internal static string REMOVE_API_TITLE {
            get {
                return ResourceManager.GetString("REMOVE_API_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selektierte API entfernen ähnelt.
        /// </summary>
        internal static string REMOVE_SELECTED_API {
            get {
                return ResourceManager.GetString("REMOVE_SELECTED_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchtest du wirklich diesen Server von deinen Favoriten löschen? ähnelt.
        /// </summary>
        internal static string REMOVE_SERVER_FROM_FAVOURITES {
            get {
                return ResourceManager.GetString("REMOVE_SERVER_FROM_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favorit entfernen ähnelt.
        /// </summary>
        internal static string REMOVE_SERVER_FROM_FAVOURITES_TITLE {
            get {
                return ResourceManager.GetString("REMOVE_SERVER_FROM_FAVOURITES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchtest du wirklich die API Liste zu ihrem Ursprungszustand zurücksetzen? ähnelt.
        /// </summary>
        internal static string REVERT_API_LIST {
            get {
                return ResourceManager.GetString("REVERT_API_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API Liste zurücksetzen ähnelt.
        /// </summary>
        internal static string REVERT_API_LIST_TITLE {
            get {
                return ResourceManager.GetString("REVERT_API_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen zurückstellen ähnelt.
        /// </summary>
        internal static string REVERT_CONFIG {
            get {
                return ResourceManager.GetString("REVERT_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Russisch (Русский) ähnelt.
        /// </summary>
        internal static string RUSSIAN {
            get {
                return ResourceManager.GetString("RUSSIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gespeicherte Positionen ähnelt.
        /// </summary>
        internal static string SAVED_POSITIONS {
            get {
                return ResourceManager.GetString("SAVED_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle eine Server Liste aus ähnelt.
        /// </summary>
        internal static string SELECT_API {
            get {
                return ResourceManager.GetString("SELECT_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Selektiere Favoritenliste ähnelt.
        /// </summary>
        internal static string SELECT_FAVOURITE_LIST_TITLE {
            get {
                return ResourceManager.GetString("SELECT_FAVOURITE_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selektiere Favoritenliste ähnelt.
        /// </summary>
        internal static string SELECT_FAVOURITES_LIST {
            get {
                return ResourceManager.GetString("SELECT_FAVOURITES_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache auswählen (Select language) ähnelt.
        /// </summary>
        internal static string SELECT_LANGUAGE {
            get {
                return ResourceManager.GetString("SELECT_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle eine Serverliste aus ähnelt.
        /// </summary>
        internal static string SELECT_SERVER_LIST {
            get {
                return ResourceManager.GetString("SELECT_SERVER_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieser Server ist bereits in deinen Favoriten. ähnelt.
        /// </summary>
        internal static string SERVER_ALREADY_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("SERVER_ALREADY_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieser Server ist nicht in deinen Favoriten. ähnelt.
        /// </summary>
        internal static string SERVER_NOT_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("SERVER_NOT_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server Passwort ähnelt.
        /// </summary>
        internal static string SERVER_PASSWORD {
            get {
                return ResourceManager.GetString("SERVER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server Passwort Eingabefeld ist leer.\r\n\r\nMöchtest du fortfahren? ähnelt.
        /// </summary>
        internal static string SERVER_PASSWORD_FIELD_IS_EMPTY {
            get {
                return ResourceManager.GetString("SERVER_PASSWORD_FIELD_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server Passwort Einagefeld ist leer. ähnelt.
        /// </summary>
        internal static string SERVER_PASSWORD_FIELD_IS_EMPTY_TITLE {
            get {
                return ResourceManager.GetString("SERVER_PASSWORD_FIELD_IS_EMPTY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server ähnelt.
        /// </summary>
        internal static string SERVERS {
            get {
                return ResourceManager.GetString("SERVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server Filter ähnelt.
        /// </summary>
        internal static string SERVERS_FILTER {
            get {
                return ResourceManager.GetString("SERVERS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erweiterte Serverinformationen ähnelt.
        /// </summary>
        internal static string SHOW_EXTENDED_SERVER_INFORMATION {
            get {
                return ResourceManager.GetString("SHOW_EXTENDED_SERVER_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favoriten ähnelt.
        /// </summary>
        internal static string SHOW_FAVOURITES {
            get {
                return ResourceManager.GetString("SHOW_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeige Gallery ähnelt.
        /// </summary>
        internal static string SHOW_GALLERY {
            get {
                return ResourceManager.GetString("SHOW_GALLERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeige letzten Chatprotokoll... ähnelt.
        /// </summary>
        internal static string SHOW_LAST_CHATLOG {
            get {
                return ResourceManager.GetString("SHOW_LAST_CHATLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abw. komp. Favoriten ähnelt.
        /// </summary>
        internal static string SHOW_LEGACY_FAVOURITES {
            get {
                return ResourceManager.GetString("SHOW_LEGACY_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hosted Liste ähnelt.
        /// </summary>
        internal static string SHOW_LEGACY_HOSTED_LIST {
            get {
                return ResourceManager.GetString("SHOW_LEGACY_HOSTED_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Master Liste ähnelt.
        /// </summary>
        internal static string SHOW_LEGACY_MASTER_LIST {
            get {
                return ResourceManager.GetString("SHOW_LEGACY_MASTER_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzernamen nicht speichern ähnelt.
        /// </summary>
        internal static string TEMPORARY_USERNAME {
            get {
                return ResourceManager.GetString("TEMPORARY_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeitstempel ähnelt.
        /// </summary>
        internal static string TIMESTAMP {
            get {
                return ResourceManager.GetString("TIMESTAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzername ähnelt.
        /// </summary>
        internal static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
    }
}
