//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPLauncherNET.Languages {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class nl_BE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal nl_BE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAMPLauncherNET.Languages.nl-BE", typeof(nl_BE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Over ähnelt.
        /// </summary>
        internal static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///SAMPLauncher NET is een client voor San Andreas Multiplayer.
        ///
        ///Deze software is altijd gratis en is erkend met GPLv3.
        ///
        ///Dit project bevind zich op ähnelt.
        /// </summary>
        internal static string ABOUT_DESCRIPTION {
            get {
                return ResourceManager.GetString("ABOUT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erkent limiet ähnelt.
        /// </summary>
        internal static string ACKNOWLEDGES_LIMIT {
            get {
                return ResourceManager.GetString("ACKNOWLEDGES_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adres voor favorieten ähnelt.
        /// </summary>
        internal static string ADD_ADDRESS_TO_FAVOURITE_LIST {
            get {
                return ResourceManager.GetString("ADD_ADDRESS_TO_FAVOURITE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Adres voor favorieten ähnelt.
        /// </summary>
        internal static string ADD_ADDRESS_TO_FAVOURITE_LIST_TITLE {
            get {
                return ResourceManager.GetString("ADD_ADDRESS_TO_FAVOURITE_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voeg nieuwe API toe ähnelt.
        /// </summary>
        internal static string ADD_NEW_API {
            get {
                return ResourceManager.GetString("ADD_NEW_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voeg een nieuwe plugin toe ähnelt.
        /// </summary>
        internal static string ADD_NEW_PLUGIN {
            get {
                return ResourceManager.GetString("ADD_NEW_PLUGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voeg server toe bij favorieten ähnelt.
        /// </summary>
        internal static string ADD_SERVER_TO_FAVOURITES {
            get {
                return ResourceManager.GetString("ADD_SERVER_TO_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bestaat al in favorieten ähnelt.
        /// </summary>
        internal static string ALREADY_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("ALREADY_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kondig server aan ähnelt.
        /// </summary>
        internal static string ANNOUNCE {
            get {
                return ResourceManager.GetString("ANNOUNCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API ähnelt.
        /// </summary>
        internal static string API {
            get {
                return ResourceManager.GetString("API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API endpoint ähnelt.
        /// </summary>
        internal static string API_ENDPOINT {
            get {
                return ResourceManager.GetString("API_ENDPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gelieve een geldig API endpoint te geven ähnelt.
        /// </summary>
        internal static string API_ENDPOINT_MISSING {
            get {
                return ResourceManager.GetString("API_ENDPOINT_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API endpoint ontbreekt ähnelt.
        /// </summary>
        internal static string API_ENDPOINT_MISSING_TITLE {
            get {
                return ResourceManager.GetString("API_ENDPOINT_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API naam ähnelt.
        /// </summary>
        internal static string API_NAME {
            get {
                return ResourceManager.GetString("API_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gelieve een API naam te geven. ähnelt.
        /// </summary>
        internal static string API_NAME_MISSING {
            get {
                return ResourceManager.GetString("API_NAME_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API naam ontbreekt ähnelt.
        /// </summary>
        internal static string API_NAME_MISSING_TITLE {
            get {
                return ResourceManager.GetString("API_NAME_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API type ähnelt.
        /// </summary>
        internal static string API_TYPE {
            get {
                return ResourceManager.GetString("API_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gelieve een API type te geven. ähnelt.
        /// </summary>
        internal static string API_TYPE_MISSING {
            get {
                return ResourceManager.GetString("API_TYPE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API type ontbreekt ähnelt.
        /// </summary>
        internal static string API_TYPE_MISSING_TITLE {
            get {
                return ResourceManager.GetString("API_TYPE_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assemblage versie ähnelt.
        /// </summary>
        internal static string ASSEMBLY_VERSION {
            get {
                return ResourceManager.GetString("ASSEMBLY_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audio bericht uit ähnelt.
        /// </summary>
        internal static string AUDIO_MESSAGE_OFF {
            get {
                return ResourceManager.GetString("AUDIO_MESSAGE_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audio proxy uit ähnelt.
        /// </summary>
        internal static string AUDIO_PROXY_OFF {
            get {
                return ResourceManager.GetString("AUDIO_PROXY_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bind het IP-adres ähnelt.
        /// </summary>
        internal static string BIND {
            get {
                return ResourceManager.GetString("BIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Annuleer ähnelt.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wilt u de download echt annuleren? ähnelt.
        /// </summary>
        internal static string CANCEL_DOWNLOAD {
            get {
                return ResourceManager.GetString("CANCEL_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Annuleer de download ähnelt.
        /// </summary>
        internal static string CANCEL_DOWNLOAD_TITLE {
            get {
                return ResourceManager.GetString("CANCEL_DOWNLOAD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chatregistratie inschakelen ähnelt.
        /// </summary>
        internal static string CHAT_LOGGING {
            get {
                return ResourceManager.GetString("CHAT_LOGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chatgeschiedenis ähnelt.
        /// </summary>
        internal static string CHATLOG {
            get {
                return ResourceManager.GetString("CHATLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HTML kopiëren ähnelt.
        /// </summary>
        internal static string CHATLOG_COPY_HTML {
            get {
                return ResourceManager.GetString("CHATLOG_COPY_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kopieer de originele tekst ähnelt.
        /// </summary>
        internal static string CHATLOG_COPY_ORIGINAL_TEXT {
            get {
                return ResourceManager.GetString("CHATLOG_COPY_ORIGINAL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kopieer RTF ähnelt.
        /// </summary>
        internal static string CHATLOG_COPY_RTF {
            get {
                return ResourceManager.GetString("CHATLOG_COPY_RTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kopieer tekst ähnelt.
        /// </summary>
        internal static string CHATLOG_COPY_TEXT {
            get {
                return ResourceManager.GetString("CHATLOG_COPY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kleurcodes ähnelt.
        /// </summary>
        internal static string CHATLOG_OPTION_COLOR_CODES {
            get {
                return ResourceManager.GetString("CHATLOG_OPTION_COLOR_CODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die gekleurde ähnelt.
        /// </summary>
        internal static string CHATLOG_OPTION_COLORED {
            get {
                return ResourceManager.GetString("CHATLOG_OPTION_COLORED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tijdstempel ähnelt.
        /// </summary>
        internal static string CHATLOG_OPTION_TIMESTAMP {
            get {
                return ResourceManager.GetString("CHATLOG_OPTION_TIMESTAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sla HTML op als... ähnelt.
        /// </summary>
        internal static string CHATLOG_SAVE_HTML_AS {
            get {
                return ResourceManager.GetString("CHATLOG_SAVE_HTML_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sla originele tekst op als... ähnelt.
        /// </summary>
        internal static string CHATLOG_SAVE_ORIGINAL_TEXT_AS {
            get {
                return ResourceManager.GetString("CHATLOG_SAVE_ORIGINAL_TEXT_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sla RTF op als... ähnelt.
        /// </summary>
        internal static string CHATLOG_SAVE_RTF_AS {
            get {
                return ResourceManager.GetString("CHATLOG_SAVE_RTF_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tekst opslaan als... ähnelt.
        /// </summary>
        internal static string CHATLOG_SAVE_TEXT_AS {
            get {
                return ResourceManager.GetString("CHATLOG_SAVE_TEXT_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stad ähnelt.
        /// </summary>
        internal static string CITY {
            get {
                return ResourceManager.GetString("CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sluit wanneer gestart ähnelt.
        /// </summary>
        internal static string CLOSE_WHEN_LAUNCHED {
            get {
                return ResourceManager.GetString("CLOSE_WHEN_LAUNCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connecteer ähnelt.
        /// </summary>
        internal static string CONNECT {
            get {
                return ResourceManager.GetString("CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connecteer nu! ähnelt.
        /// </summary>
        internal static string CONNECT_NOW {
            get {
                return ResourceManager.GetString("CONNECT_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Connecteer ähnelt.
        /// </summary>
        internal static string CONNECT_TITLE {
            get {
                return ResourceManager.GetString("CONNECT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbind met adres ähnelt.
        /// </summary>
        internal static string CONNECT_TO_ADDRESS {
            get {
                return ResourceManager.GetString("CONNECT_TO_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Verbind met adres ähnelt.
        /// </summary>
        internal static string CONNECT_TO_ADDRESS_TITLE {
            get {
                return ResourceManager.GetString("CONNECT_TO_ADDRESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maak verbinding met de testserver ähnelt.
        /// </summary>
        internal static string CONNECT_TO_TEST_SERVER {
            get {
                return ResourceManager.GetString("CONNECT_TO_TEST_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connecteer met RCON ähnelt.
        /// </summary>
        internal static string CONNECT_WITH_RCON {
            get {
                return ResourceManager.GetString("CONNECT_WITH_RCON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbindingscookies toestaan ähnelt.
        /// </summary>
        internal static string CONNECTION_COOKIES {
            get {
                return ResourceManager.GetString("CONNECTION_COOKIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aansluiting zaaitijd ähnelt.
        /// </summary>
        internal static string CONNECTION_SEED_TIME {
            get {
                return ResourceManager.GetString("CONNECTION_SEED_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schakel cookieregistratie in ähnelt.
        /// </summary>
        internal static string COOKIE_LOGGING {
            get {
                return ResourceManager.GetString("COOKIE_LOGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Land ähnelt.
        /// </summary>
        internal static string COUNTRY {
            get {
                return ResourceManager.GetString("COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maak sessielogboek ähnelt.
        /// </summary>
        internal static string CREATE_SESSIONS_LOG {
            get {
                return ResourceManager.GetString("CREATE_SESSIONS_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database log query&apos;s ähnelt.
        /// </summary>
        internal static string DATABASE_LOG_QUERIES {
            get {
                return ResourceManager.GetString("DATABASE_LOG_QUERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schakel databaselogging in ähnelt.
        /// </summary>
        internal static string DATABASE_LOGGING {
            get {
                return ResourceManager.GetString("DATABASE_LOGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum en tijd ähnelt.
        /// </summary>
        internal static string DATE_AND_TIME {
            get {
                return ResourceManager.GetString("DATE_AND_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debug mode ähnelt.
        /// </summary>
        internal static string DEBUG_MODE {
            get {
                return ResourceManager.GetString("DEBUG_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verwijder ähnelt.
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ben je zeker dat je de geselecteerde afbeeldingen wilt verwijderen? ähnelt.
        /// </summary>
        internal static string DELETE_SELECTED_IMAGES {
            get {
                return ResourceManager.GetString("DELETE_SELECTED_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verwijder geselecteerd afbeeldingen ähnelt.
        /// </summary>
        internal static string DELETE_SELECTED_IMAGES_TITLE {
            get {
                return ResourceManager.GetString("DELETE_SELECTED_IMAGES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ontwikkelaarstools ähnelt.
        /// </summary>
        internal static string DEVELOPER_TOOLS {
            get {
                return ResourceManager.GetString("DEVELOPER_TOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Configuratie van ontwikkelaarstools ähnelt.
        /// </summary>
        internal static string DEVELOPER_TOOLS_CONFIGURATION_TITLE {
            get {
                return ResourceManager.GetString("DEVELOPER_TOOLS_CONFIGURATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ontwikkelingsdirectory ähnelt.
        /// </summary>
        internal static string DEVELOPMENT_DIRECTORY {
            get {
                return ResourceManager.GetString("DEVELOPMENT_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leid naar scherm textdraw render methode (langzaam) ähnelt.
        /// </summary>
        internal static string DIRECT_MODE {
            get {
                return ResourceManager.GetString("DIRECT_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schakel hoofdbeweging uit ähnelt.
        /// </summary>
        internal static string DISABLE_HEAD_MOVE {
            get {
                return ResourceManager.GetString("DISABLE_HEAD_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download mislukt ähnelt.
        /// </summary>
        internal static string DOWNLOAD_FAILED_TITLE {
            get {
                return ResourceManager.GetString("DOWNLOAD_FAILED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloaden ähnelt.
        /// </summary>
        internal static string DOWNLOAD_PROGRESS {
            get {
                return ResourceManager.GetString("DOWNLOAD_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voortgang downloaden ähnelt.
        /// </summary>
        internal static string DOWNLOAD_PROGRESS_TITLE {
            get {
                return ResourceManager.GetString("DOWNLOAD_PROGRESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nederlands ähnelt.
        /// </summary>
        internal static string DUTCH {
            get {
                return ResourceManager.GetString("DUTCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - wijzig API ähnelt.
        /// </summary>
        internal static string EDIT_API_TITLE {
            get {
                return ResourceManager.GetString("EDIT_API_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Bewerk plugin ähnelt.
        /// </summary>
        internal static string EDIT_PLUGIN_TITLE {
            get {
                return ResourceManager.GetString("EDIT_PLUGIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wijzig geselecteerde API ähnelt.
        /// </summary>
        internal static string EDIT_SELECTED_API {
            get {
                return ResourceManager.GetString("EDIT_SELECTED_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bewerk geselecteerde plug-in ähnelt.
        /// </summary>
        internal static string EDIT_SELECTED_PLUGIN {
            get {
                return ResourceManager.GetString("EDIT_SELECTED_PLUGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eindpunt ähnelt.
        /// </summary>
        internal static string ENDPOINT {
            get {
                return ResourceManager.GetString("ENDPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Engels (English) ähnelt.
        /// </summary>
        internal static string ENGLISH {
            get {
                return ResourceManager.GetString("ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Uitgebreide server informatie ähnelt.
        /// </summary>
        internal static string EXTENDED_SERVER_INFORMATION_TITLE {
            get {
                return ResourceManager.GetString("EXTENDED_SERVER_INFORMATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selecteer alstublieft een favorietenlijst. ähnelt.
        /// </summary>
        internal static string FAVOURITE_LIST_NOT_SELECTED {
            get {
                return ResourceManager.GetString("FAVOURITE_LIST_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favorietenlijst niet geselecteerd ähnelt.
        /// </summary>
        internal static string FAVOURITE_LIST_NOT_SELECTED_TITLE {
            get {
                return ResourceManager.GetString("FAVOURITE_LIST_NOT_SELECTED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bestandsversie ähnelt.
        /// </summary>
        internal static string FILE_VERSION {
            get {
                return ResourceManager.GetString("FILE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter hostname ähnelt.
        /// </summary>
        internal static string FILTER_HOSTNAME {
            get {
                return ResourceManager.GetString("FILTER_HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter IP en poort ähnelt.
        /// </summary>
        internal static string FILTER_IP_AND_PORT {
            get {
                return ResourceManager.GetString("FILTER_IP_AND_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter taal ähnelt.
        /// </summary>
        internal static string FILTER_LANGUAGE {
            get {
                return ResourceManager.GetString("FILTER_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter mode ähnelt.
        /// </summary>
        internal static string FILTER_MODE {
            get {
                return ResourceManager.GetString("FILTER_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gebruik regex ähnelt.
        /// </summary>
        internal static string FILTER_USE_REGEX {
            get {
                return ResourceManager.GetString("FILTER_USE_REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter scripts ähnelt.
        /// </summary>
        internal static string FILTERSCRIPTS {
            get {
                return ResourceManager.GetString("FILTERSCRIPTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font-face ähnelt.
        /// </summary>
        internal static string FONT_FACE {
            get {
                return ResourceManager.GetString("FONT_FACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font-weight ähnelt.
        /// </summary>
        internal static string FONT_WEIGHT {
            get {
                return ResourceManager.GetString("FONT_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FPS limit ähnelt.
        /// </summary>
        internal static string FPS_LIMIT {
            get {
                return ResourceManager.GetString("FPS_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game-versie ähnelt.
        /// </summary>
        internal static string GAME_VERSION {
            get {
                return ResourceManager.GetString("GAME_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gamemode ähnelt.
        /// </summary>
        internal static string GAMEMODE {
            get {
                return ResourceManager.GetString("GAMEMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gamemode tekst ähnelt.
        /// </summary>
        internal static string GAMEMODE_TEXT {
            get {
                return ResourceManager.GetString("GAMEMODE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gamemodes ähnelt.
        /// </summary>
        internal static string GAMEMODES {
            get {
                return ResourceManager.GetString("GAMEMODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Georgisch (ქართული) ähnelt.
        /// </summary>
        internal static string GEORGIAN {
            get {
                return ResourceManager.GetString("GEORGIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duits (Deutsch) ähnelt.
        /// </summary>
        internal static string GERMAN {
            get {
                return ResourceManager.GetString("GERMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GitHub project SAMPLauncherNET ähnelt.
        /// </summary>
        internal static string GITHUB_PROJECT {
            get {
                return ResourceManager.GetString("GITHUB_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Een exemplaar van GTA San Andreas wordt nu uitgevoerd. Het wordt beëindigd voordat een nieuw exemplaar wordt gemaakt.
        ///
        ///Wil je doorgaan? ähnelt.
        /// </summary>
        internal static string GTA_SA_IS_RUNNING {
            get {
                return ResourceManager.GetString("GTA_SA_IS_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GTA San Andreas is aan het rennen ähnelt.
        /// </summary>
        internal static string GTA_SA_IS_RUNNING_TITLE {
            get {
                return ResourceManager.GetString("GTA_SA_IS_RUNNING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Host en haven ähnelt.
        /// </summary>
        internal static string HOST_AND_PORT {
            get {
                return ResourceManager.GetString("HOST_AND_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Host naam ähnelt.
        /// </summary>
        internal static string HOSTNAME {
            get {
                return ResourceManager.GetString("HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID ähnelt.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schakel IME (Input Method Editor) in ähnelt.
        /// </summary>
        internal static string IME {
            get {
                return ResourceManager.GetString("IME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In tick rate van de auto ähnelt.
        /// </summary>
        internal static string IN_CAR_RATE {
            get {
                return ResourceManager.GetString("IN_CAR_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input error ähnelt.
        /// </summary>
        internal static string INPUT_ERROR {
            get {
                return ResourceManager.GetString("INPUT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vul hier een filter... ähnelt.
        /// </summary>
        internal static string INSERT_FILTER_HERE {
            get {
                return ResourceManager.GetString("INSERT_FILTER_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vul hier een RCON password in... ähnelt.
        /// </summary>
        internal static string INSERT_RCON_PASSWORD_HERE {
            get {
                return ResourceManager.GetString("INSERT_RCON_PASSWORD_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vul hier een server password in... ähnelt.
        /// </summary>
        internal static string INSERT_SERVER_PASSWORD_HERE {
            get {
                return ResourceManager.GetString("INSERT_SERVER_PASSWORD_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vul hier een spelernaam in... ähnelt.
        /// </summary>
        internal static string INSERT_USERNAME_HERE {
            get {
                return ResourceManager.GetString("INSERT_USERNAME_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wilt u echt {0} installeren? ähnelt.
        /// </summary>
        internal static string INSTALL_VERSION {
            get {
                return ResourceManager.GetString("INSTALL_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installeer versie ähnelt.
        /// </summary>
        internal static string INSTALL_VERSION_TITLE {
            get {
                return ResourceManager.GetString("INSTALL_VERSION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP and poort ähnelt.
        /// </summary>
        internal static string IP_AND_PORT {
            get {
                return ResourceManager.GetString("IP_AND_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lag compensatiemodus ähnelt.
        /// </summary>
        internal static string LAG_COMPENSATION_MODE {
            get {
                return ResourceManager.GetString("LAG_COMPENSATION_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LAN-modus ähnelt.
        /// </summary>
        internal static string LAN_MODE {
            get {
                return ResourceManager.GetString("LAN_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taal ähnelt.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breedtegraad en lengtegraad ähnelt.
        /// </summary>
        internal static string LATITUDE_LONGITUDE {
            get {
                return ResourceManager.GetString("LATITUDE_LONGITUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start debug mode ähnelt.
        /// </summary>
        internal static string LAUNCH_DEBUG_MODE {
            get {
                return ResourceManager.GetString("LAUNCH_DEBUG_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start singleplayer ähnelt.
        /// </summary>
        internal static string LAUNCH_SINGLEPLAYER {
            get {
                return ResourceManager.GetString("LAUNCH_SINGLEPLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Launcher ähnelt.
        /// </summary>
        internal static string LAUNCHER_TITLE {
            get {
                return ResourceManager.GetString("LAUNCHER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Serverlijst wordt geladen.
        ///
        ///Dit kan even duren ... ähnelt.
        /// </summary>
        internal static string LOADING {
            get {
                return ResourceManager.GetString("LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log vragen ähnelt.
        /// </summary>
        internal static string LOG_QUERIES {
            get {
                return ResourceManager.GetString("LOG_QUERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log time format ähnelt.
        /// </summary>
        internal static string LOG_TIME_FORMAT {
            get {
                return ResourceManager.GetString("LOG_TIME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kaart naam ähnelt.
        /// </summary>
        internal static string MAP_NAME {
            get {
                return ResourceManager.GetString("MAP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximale NPC&apos;s ähnelt.
        /// </summary>
        internal static string MAXIMAL_NPCS {
            get {
                return ResourceManager.GetString("MAXIMAL_NPCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximale spelers ähnelt.
        /// </summary>
        internal static string MAXIMAL_PLAYERS {
            get {
                return ResourceManager.GetString("MAXIMAL_PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Media ähnelt.
        /// </summary>
        internal static string MEDIA {
            get {
                return ResourceManager.GetString("MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Limiet berichtberichten ähnelt.
        /// </summary>
        internal static string MESSAGE_HOLE_LIMIT {
            get {
                return ResourceManager.GetString("MESSAGE_HOLE_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Berichten beperken ähnelt.
        /// </summary>
        internal static string MESSAGES_LIMIT {
            get {
                return ResourceManager.GetString("MESSAGES_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Metro code ähnelt.
        /// </summary>
        internal static string METRO_CODE {
            get {
                return ResourceManager.GetString("METRO_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimale verbindingstijd ähnelt.
        /// </summary>
        internal static string MINIMUM_CONNECTION_TIME {
            get {
                return ResourceManager.GetString("MINIMUM_CONNECTION_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mode ähnelt.
        /// </summary>
        internal static string MODE {
            get {
                return ResourceManager.GetString("MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multi core ähnelt.
        /// </summary>
        internal static string MULTI_CORE {
            get {
                return ResourceManager.GetString("MULTI_CORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Naam ähnelt.
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hulp nodig? Ga naar SA:MP forums... ähnelt.
        /// </summary>
        internal static string NEED_HELP_FORUMS {
            get {
                return ResourceManager.GetString("NEED_HELP_FORUMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Voeg nieuwe API toe ähnelt.
        /// </summary>
        internal static string NEW_API_TITLE {
            get {
                return ResourceManager.GetString("NEW_API_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Voeg een nieuwe plugin toe ähnelt.
        /// </summary>
        internal static string NEW_PLUGIN_TITLE {
            get {
                return ResourceManager.GetString("NEW_PLUGIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geef een adres op om toe te voegen aan uw favorietenlijst. ähnelt.
        /// </summary>
        internal static string NO_ADDRESS_SPECIFIED {
            get {
                return ResourceManager.GetString("NO_ADDRESS_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geen adres opgegeven ähnelt.
        /// </summary>
        internal static string NO_ADDRESS_SPECIFIED_TITLE {
            get {
                return ResourceManager.GetString("NO_ADDRESS_SPECIFIED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geen chatlog gevonden... ähnelt.
        /// </summary>
        internal static string NO_CHATLOG_FOUND {
            get {
                return ResourceManager.GetString("NO_CHATLOG_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Er zijn geen favorietenlijsten gedefinieerd. Als u een nieuwe lijst wilt definiëren, selecteert u het tabblad &apos;API&apos; en maakt u een nieuwe favorietenlijst of herstel naar de standaardinstellingen. ähnelt.
        /// </summary>
        internal static string NO_FAVOURITES {
            get {
                return ResourceManager.GetString("NO_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geen favoriete lijsten ähnelt.
        /// </summary>
        internal static string NO_FAVOURITES_TITLE {
            get {
                return ResourceManager.GetString("NO_FAVOURITES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geen naam tag status ähnelt.
        /// </summary>
        internal static string NO_NAMETAG_STATUS {
            get {
                return ResourceManager.GetString("NO_NAMETAG_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Er is geen sessielogboek gemaakt.
        ///
        ///Zie opties om die functie in te schakelen. ähnelt.
        /// </summary>
        internal static string NO_SESSION_LOG {
            get {
                return ResourceManager.GetString("NO_SESSION_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geen teken ähnelt.
        /// </summary>
        internal static string NO_SIGN {
            get {
                return ResourceManager.GetString("NO_SIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Niet in favorieten ähnelt.
        /// </summary>
        internal static string NOT_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("NOT_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Te voet tick rate ähnelt.
        /// </summary>
        internal static string ON_FOOT_RATE {
            get {
                return ResourceManager.GetString("ON_FOOT_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open de map ähnelt.
        /// </summary>
        internal static string OPEN_DIRECTORY {
            get {
                return ResourceManager.GetString("OPEN_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Openen in verkenner ähnelt.
        /// </summary>
        internal static string OPEN_IN_EXPLORER {
            get {
                return ResourceManager.GetString("OPEN_IN_EXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opties ähnelt.
        /// </summary>
        internal static string OPTIONS {
            get {
                return ResourceManager.GetString("OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Opties ähnelt.
        /// </summary>
        internal static string OPTIONS_TITLE {
            get {
                return ResourceManager.GetString("OPTIONS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pagina grootte ähnelt.
        /// </summary>
        internal static string PAGE_SIZE {
            get {
                return ResourceManager.GetString("PAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wachtwoord ähnelt.
        /// </summary>
        internal static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wilt u uw versie echt naar {0} patchen? ähnelt.
        /// </summary>
        internal static string PATCH_VERSION {
            get {
                return ResourceManager.GetString("PATCH_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Patch-versie ähnelt.
        /// </summary>
        internal static string PATCH_VERSION_TITLE {
            get {
                return ResourceManager.GetString("PATCH_VERSION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ping ähnelt.
        /// </summary>
        internal static string PING {
            get {
                return ResourceManager.GetString("PING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speler ähnelt.
        /// </summary>
        internal static string PLAYER {
            get {
                return ResourceManager.GetString("PLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time-out van speler ähnelt.
        /// </summary>
        internal static string PLAYER_TIME_OUT {
            get {
                return ResourceManager.GetString("PLAYER_TIME_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spelers ähnelt.
        /// </summary>
        internal static string PLAYERS {
            get {
                return ResourceManager.GetString("PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gelieve een gebruikersnaam in te vullen. ähnelt.
        /// </summary>
        internal static string PLEASE_TYPE_IN_USERNAME {
            get {
                return ResourceManager.GetString("PLEASE_TYPE_IN_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin kan niet worden gekopieerd. ähnelt.
        /// </summary>
        internal static string PLUGIN_COPY_ERROR {
            get {
                return ResourceManager.GetString("PLUGIN_COPY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schakel plug-in in ähnelt.
        /// </summary>
        internal static string PLUGIN_ENABLED {
            get {
                return ResourceManager.GetString("PLUGIN_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin-fout ähnelt.
        /// </summary>
        internal static string PLUGIN_ERROR_TITLE {
            get {
                return ResourceManager.GetString("PLUGIN_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin naam ähnelt.
        /// </summary>
        internal static string PLUGIN_NAME {
            get {
                return ResourceManager.GetString("PLUGIN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voer een API-naam in. ähnelt.
        /// </summary>
        internal static string PLUGIN_NAME_MISSING {
            get {
                return ResourceManager.GetString("PLUGIN_NAME_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Naam van plug-in ontbreekt ähnelt.
        /// </summary>
        internal static string PLUGIN_NAME_MISSING_TITLE {
            get {
                return ResourceManager.GetString("PLUGIN_NAME_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin-provider ähnelt.
        /// </summary>
        internal static string PLUGIN_PROVIDER {
            get {
                return ResourceManager.GetString("PLUGIN_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geef een pluginprovider op ähnelt.
        /// </summary>
        internal static string PLUGIN_PROVIDER_MISSING {
            get {
                return ResourceManager.GetString("PLUGIN_PROVIDER_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin-provider ontbreekt ähnelt.
        /// </summary>
        internal static string PLUGIN_PROVIDER_MISSING_TITLE {
            get {
                return ResourceManager.GetString("PLUGIN_PROVIDER_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update-frequentie van plug-in ähnelt.
        /// </summary>
        internal static string PLUGIN_UPDATE_FREQUENCY {
            get {
                return ResourceManager.GetString("PLUGIN_UPDATE_FREQUENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geef een update-frequentie voor de plug-in op ähnelt.
        /// </summary>
        internal static string PLUGIN_UPDATE_FREQUENCY_MISSING {
            get {
                return ResourceManager.GetString("PLUGIN_UPDATE_FREQUENCY_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update-frequentie van plug-in ontbreekt ähnelt.
        /// </summary>
        internal static string PLUGIN_UPDATE_FREQUENCY_MISSING_TITLE {
            get {
                return ResourceManager.GetString("PLUGIN_UPDATE_FREQUENCY_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die URI plug-in ähnelt.
        /// </summary>
        internal static string PLUGIN_URI {
            get {
                return ResourceManager.GetString("PLUGIN_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geef een plug-in URI op ähnelt.
        /// </summary>
        internal static string PLUGIN_URI_MISSING {
            get {
                return ResourceManager.GetString("PLUGIN_URI_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plug-in URI ontbreekt ähnelt.
        /// </summary>
        internal static string PLUGIN_URI_MISSING_TITLE {
            get {
                return ResourceManager.GetString("PLUGIN_URI_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugins ähnelt.
        /// </summary>
        internal static string PLUGINS {
            get {
                return ResourceManager.GetString("PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Port ähnelt.
        /// </summary>
        internal static string PORT {
            get {
                return ResourceManager.GetString("PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Portugees (Português) ähnelt.
        /// </summary>
        internal static string PORTUGUESE {
            get {
                return ResourceManager.GetString("PORTUGUESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Portugees Brazilië (Português de Brasil) ähnelt.
        /// </summary>
        internal static string PORTUGUESE_BRAZIL {
            get {
                return ResourceManager.GetString("PORTUGUESE_BRAZIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Product versie ähnelt.
        /// </summary>
        internal static string PRODUCT_VERSION {
            get {
                return ResourceManager.GetString("PRODUCT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schakel vraag in ähnelt.
        /// </summary>
        internal static string QUERY {
            get {
                return ResourceManager.GetString("QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schakel RCON in ähnelt.
        /// </summary>
        internal static string RCON {
            get {
                return ResourceManager.GetString("RCON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RCON wachtwoord ähnelt.
        /// </summary>
        internal static string RCON_PASSWORD {
            get {
                return ResourceManager.GetString("RCON_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - RCON wachtwoord ähnelt.
        /// </summary>
        internal static string RCON_PASSWORD_TITLE {
            get {
                return ResourceManager.GetString("RCON_PASSWORD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Regio ähnelt.
        /// </summary>
        internal static string REGION {
            get {
                return ResourceManager.GetString("REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Herlaad serverlijsten ähnelt.
        /// </summary>
        internal static string RELOAD_SERVER_LISTS {
            get {
                return ResourceManager.GetString("RELOAD_SERVER_LISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wil je de geselecteerde API echt verwijderen? ähnelt.
        /// </summary>
        internal static string REMOVE_API {
            get {
                return ResourceManager.GetString("REMOVE_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verwijder geselecteerde API ähnelt.
        /// </summary>
        internal static string REMOVE_API_TITLE {
            get {
                return ResourceManager.GetString("REMOVE_API_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wilt u echt de geselecteerde plug-in verwijderen? ähnelt.
        /// </summary>
        internal static string REMOVE_PLUGIN {
            get {
                return ResourceManager.GetString("REMOVE_PLUGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verwijder de geselecteerde plug-in ähnelt.
        /// </summary>
        internal static string REMOVE_PLUGIN_TITLE {
            get {
                return ResourceManager.GetString("REMOVE_PLUGIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verwijder geselecteerde API ähnelt.
        /// </summary>
        internal static string REMOVE_SELECTED_API {
            get {
                return ResourceManager.GetString("REMOVE_SELECTED_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verwijder de geselecteerde plug-in ähnelt.
        /// </summary>
        internal static string REMOVE_SELECTED_PLUGIN {
            get {
                return ResourceManager.GetString("REMOVE_SELECTED_PLUGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wil je deze server echt uit je favorieten verwijderen? ähnelt.
        /// </summary>
        internal static string REMOVE_SERVER_FROM_FAVOURITES {
            get {
                return ResourceManager.GetString("REMOVE_SERVER_FROM_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verwijder server uit favorieten ähnelt.
        /// </summary>
        internal static string REMOVE_SERVER_FROM_FAVOURITES_TITLE {
            get {
                return ResourceManager.GetString("REMOVE_SERVER_FROM_FAVOURITES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ben je zeker dat je de standaardwaarden terug wilt zetten in de API lijst? ähnelt.
        /// </summary>
        internal static string REVERT_API_LIST {
            get {
                return ResourceManager.GetString("REVERT_API_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Herstel API lijst ähnelt.
        /// </summary>
        internal static string REVERT_API_LIST_TITLE {
            get {
                return ResourceManager.GetString("REVERT_API_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Herstel de configuratie naar standaardwaarden ähnelt.
        /// </summary>
        internal static string REVERT_CONFIG {
            get {
                return ResourceManager.GetString("REVERT_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wilt u echt de pluginlijst terugzetten naar de standaardwaarde? ähnelt.
        /// </summary>
        internal static string REVERT_PLUGIN_LIST {
            get {
                return ResourceManager.GetString("REVERT_PLUGIN_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zet de plugin lijst terug ähnelt.
        /// </summary>
        internal static string REVERT_PLUGIN_LIST_TITLE {
            get {
                return ResourceManager.GetString("REVERT_PLUGIN_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Regel ähnelt.
        /// </summary>
        internal static string RULE {
            get {
                return ResourceManager.GetString("RULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Russisch (Русский) ähnelt.
        /// </summary>
        internal static string RUSSIAN {
            get {
                return ResourceManager.GetString("RUSSIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sampctl-fout ähnelt.
        /// </summary>
        internal static string SAMPCTL_ERROR_TITLE {
            get {
                return ResourceManager.GetString("SAMPCTL_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installeer &quot;sampctl&quot; van {0} om een server te draaien.
        ///
        ///Wilt u deze website nu bezoeken? ähnelt.
        /// </summary>
        internal static string SAMPCTL_MISSING {
            get {
                return ResourceManager.GetString("SAMPCTL_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sampctl kan momenteel niet worden gedownload. ähnelt.
        /// </summary>
        internal static string SAMPCTL_MISSING_ASSET {
            get {
                return ResourceManager.GetString("SAMPCTL_MISSING_ASSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installatie &quot;sampctl&quot; ontbreekt ähnelt.
        /// </summary>
        internal static string SAMPCTL_MISSING_TITLE {
            get {
                return ResourceManager.GetString("SAMPCTL_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sampctl kan niet worden uitgepakt. ähnelt.
        /// </summary>
        internal static string SAMPCTL_UNZIP_ERROR {
            get {
                return ResourceManager.GetString("SAMPCTL_UNZIP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opslaan ähnelt.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Partituur ähnelt.
        /// </summary>
        internal static string SCORE {
            get {
                return ResourceManager.GetString("SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoek door... ähnelt.
        /// </summary>
        internal static string SEARCH_ON {
            get {
                return ResourceManager.GetString("SEARCH_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bing ähnelt.
        /// </summary>
        internal static string SEARCH_ON_BING {
            get {
                return ResourceManager.GetString("SEARCH_ON_BING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DuckDuckGo ähnelt.
        /// </summary>
        internal static string SEARCH_ON_DUCK_DUCK_GO {
            get {
                return ResourceManager.GetString("SEARCH_ON_DUCK_DUCK_GO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Google ähnelt.
        /// </summary>
        internal static string SEARCH_ON_GOOGLE {
            get {
                return ResourceManager.GetString("SEARCH_ON_GOOGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yahoo ähnelt.
        /// </summary>
        internal static string SEARCH_ON_YAHOO {
            get {
                return ResourceManager.GetString("SEARCH_ON_YAHOO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yandex ähnelt.
        /// </summary>
        internal static string SEARCH_ON_YANDEX {
            get {
                return ResourceManager.GetString("SEARCH_ON_YANDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die YouTube ähnelt.
        /// </summary>
        internal static string SEARCH_ON_YOU_TUBE {
            get {
                return ResourceManager.GetString("SEARCH_ON_YOU_TUBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selecteer een server lijst ähnelt.
        /// </summary>
        internal static string SELECT_API {
            get {
                return ResourceManager.GetString("SELECT_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Selecteer favoriete lijst ähnelt.
        /// </summary>
        internal static string SELECT_FAVOURITE_LIST_TITLE {
            get {
                return ResourceManager.GetString("SELECT_FAVOURITE_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selecteer favorietenlijst ähnelt.
        /// </summary>
        internal static string SELECT_FAVOURITES_LIST {
            get {
                return ResourceManager.GetString("SELECT_FAVOURITES_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selecteer taal (Select language) ähnelt.
        /// </summary>
        internal static string SELECT_LANGUAGE {
            get {
                return ResourceManager.GetString("SELECT_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selecteer server lijst ähnelt.
        /// </summary>
        internal static string SELECT_SERVER_LIST {
            get {
                return ResourceManager.GetString("SELECT_SERVER_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die U hebt geselecteerd dat {0} moet worden aangepast of handmatig moet worden geïnstalleerd.
        ///
        ///Wilt u echt {0} patchen of handmatig installeren?
        ///
        ///Druk op &quot;Ja&quot; om te patchen.
        ///Druk op &quot;Nee&quot; om te installeren.
        ///Druk op &quot;Annuleren&quot; om deze actie te annuleren. ähnelt.
        /// </summary>
        internal static string SELECT_VERSION {
            get {
                return ResourceManager.GetString("SELECT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Patch of handmatig versie installeren ähnelt.
        /// </summary>
        internal static string SELECT_VERSION_TITLE {
            get {
                return ResourceManager.GetString("SELECT_VERSION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deze server is al in je favorieten. ähnelt.
        /// </summary>
        internal static string SERVER_ALREADY_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("SERVER_ALREADY_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deze server is niet in je favorieten. ähnelt.
        /// </summary>
        internal static string SERVER_NOT_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("SERVER_NOT_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server wachtwoord ähnelt.
        /// </summary>
        internal static string SERVER_PASSWORD {
            get {
                return ResourceManager.GetString("SERVER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Het veld server wachtwoord is leeg.
        ///
        ///Doorgaan? ähnelt.
        /// </summary>
        internal static string SERVER_PASSWORD_FIELD_IS_EMPTY {
            get {
                return ResourceManager.GetString("SERVER_PASSWORD_FIELD_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veld server password is leeg ähnelt.
        /// </summary>
        internal static string SERVER_PASSWORD_FIELD_IS_EMPTY_TITLE {
            get {
                return ResourceManager.GetString("SERVER_PASSWORD_FIELD_IS_EMPTY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Servers ähnelt.
        /// </summary>
        internal static string SERVERS {
            get {
                return ResourceManager.GetString("SERVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Servers filters ähnelt.
        /// </summary>
        internal static string SERVERS_FILTER {
            get {
                return ResourceManager.GetString("SERVERS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Servers filters ähnelt.
        /// </summary>
        internal static string SERVERS_FILTERS {
            get {
                return ResourceManager.GetString("SERVERS_FILTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Sessie ähnelt.
        /// </summary>
        internal static string SESSION {
            get {
                return ResourceManager.GetString("SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wilt u deze sessie echt verwijderen? ähnelt.
        /// </summary>
        internal static string SESSION_DELETE {
            get {
                return ResourceManager.GetString("SESSION_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gooi de sessie weg ähnelt.
        /// </summary>
        internal static string SESSION_DELETE_TITLE {
            get {
                return ResourceManager.GetString("SESSION_DELETE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sessions ähnelt.
        /// </summary>
        internal static string SESSIONS {
            get {
                return ResourceManager.GetString("SESSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toon extra configuraties ähnelt.
        /// </summary>
        internal static string SHOW_ADDITIONAL_CONFIGURATIONS {
            get {
                return ResourceManager.GetString("SHOW_ADDITIONAL_CONFIGURATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toon lege servers ähnelt.
        /// </summary>
        internal static string SHOW_EMPTY_SERVERS {
            get {
                return ResourceManager.GetString("SHOW_EMPTY_SERVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uitgebreide server informatie ähnelt.
        /// </summary>
        internal static string SHOW_EXTENDED_SERVER_INFORMATION {
            get {
                return ResourceManager.GetString("SHOW_EXTENDED_SERVER_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favorieten ähnelt.
        /// </summary>
        internal static string SHOW_FAVOURITES {
            get {
                return ResourceManager.GetString("SHOW_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toon volledige servers ähnelt.
        /// </summary>
        internal static string SHOW_FULL_SERVERS {
            get {
                return ResourceManager.GetString("SHOW_FULL_SERVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toon gallerij... ähnelt.
        /// </summary>
        internal static string SHOW_GALLERY {
            get {
                return ResourceManager.GetString("SHOW_GALLERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weergeven in Google Maps ähnelt.
        /// </summary>
        internal static string SHOW_IN_GOOGLE_MAPS {
            get {
                return ResourceManager.GetString("SHOW_IN_GOOGLE_MAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weergeven in OpenStreetMap ähnelt.
        /// </summary>
        internal static string SHOW_IN_OPEN_STREET_MAP {
            get {
                return ResourceManager.GetString("SHOW_IN_OPEN_STREET_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toon laatste chatlog... ähnelt.
        /// </summary>
        internal static string SHOW_LAST_CHATLOG {
            get {
                return ResourceManager.GetString("SHOW_LAST_CHATLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legacy favorieten ähnelt.
        /// </summary>
        internal static string SHOW_LEGACY_FAVOURITES {
            get {
                return ResourceManager.GetString("SHOW_LEGACY_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hosted lijst ähnelt.
        /// </summary>
        internal static string SHOW_LEGACY_HOSTED_LIST {
            get {
                return ResourceManager.GetString("SHOW_LEGACY_HOSTED_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Master lijst ähnelt.
        /// </summary>
        internal static string SHOW_LEGACY_MASTER_LIST {
            get {
                return ResourceManager.GetString("SHOW_LEGACY_MASTER_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Officiële lijst ähnelt.
        /// </summary>
        internal static string SHOW_LEGACY_OFFICIAL_LIST {
            get {
                return ResourceManager.GetString("SHOW_LEGACY_OFFICIAL_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SACNR ähnelt.
        /// </summary>
        internal static string SHOW_SACNR_LIST {
            get {
                return ResourceManager.GetString("SHOW_SACNR_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Southclaw&apos;s lijst ähnelt.
        /// </summary>
        internal static string SHOW_SOUTHCLAWS_LIST {
            get {
                return ResourceManager.GetString("SHOW_SOUTHCLAWS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toon gebruikersnaam dialoogvenster ähnelt.
        /// </summary>
        internal static string SHOW_USERNAME_DIALOG {
            get {
                return ResourceManager.GetString("SHOW_USERNAME_DIALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bedtijd ähnelt.
        /// </summary>
        internal static string SLEEP {
            get {
                return ResourceManager.GetString("SLEEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opstartserver ähnelt.
        /// </summary>
        internal static string START_SERVER {
            get {
                return ResourceManager.GetString("START_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop server ähnelt.
        /// </summary>
        internal static string STOP_SERVER {
            get {
                return ResourceManager.GetString("STOP_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stream afstand ähnelt.
        /// </summary>
        internal static string STREAM_DISTANCE {
            get {
                return ResourceManager.GetString("STREAM_DISTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Streamsnelheid ähnelt.
        /// </summary>
        internal static string STREAM_RATE {
            get {
                return ResourceManager.GetString("STREAM_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sla gebruikersnaam niet op ähnelt.
        /// </summary>
        internal static string TEMPORARY_USERNAME {
            get {
                return ResourceManager.GetString("TEMPORARY_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tijd ähnelt.
        /// </summary>
        internal static string TIME_SPEND {
            get {
                return ResourceManager.GetString("TIME_SPEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tijdzone ähnelt.
        /// </summary>
        internal static string TIME_ZONE {
            get {
                return ResourceManager.GetString("TIME_ZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timestamp ähnelt.
        /// </summary>
        internal static string TIMESTAMP {
            get {
                return ResourceManager.GetString("TIMESTAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        internal static string TYPE {
            get {
                return ResourceManager.GetString("TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gebruikersnaam ähnelt.
        /// </summary>
        internal static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Er is al een speler met je gebruikersnaam.
        ///
        ///Wil je echt doorgaan? ähnelt.
        /// </summary>
        internal static string USERNAME_WARNING {
            get {
                return ResourceManager.GetString("USERNAME_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gebruikersnaam waarschuwing ähnelt.
        /// </summary>
        internal static string USERNAME_WARNING_TITLE {
            get {
                return ResourceManager.GetString("USERNAME_WARNING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waarde ähnelt.
        /// </summary>
        internal static string VALUE {
            get {
                return ResourceManager.GetString("VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versies ähnelt.
        /// </summary>
        internal static string VERSIONS {
            get {
                return ResourceManager.GetString("VERSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bezoek website ähnelt.
        /// </summary>
        internal static string VISIT_WEBSITE {
            get {
                return ResourceManager.GetString("VISIT_WEBSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wilt u echt deze website bezoeken? ähnelt.
        /// </summary>
        internal static string VISIT_WEBSITE_MESSAGE {
            get {
                return ResourceManager.GetString("VISIT_WEBSITE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bezoek ähnelt.
        /// </summary>
        internal static string VISIT_WEBSITE_TITLE {
            get {
                return ResourceManager.GetString("VISIT_WEBSITE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wapen snelheid ähnelt.
        /// </summary>
        internal static string WEAPON_RATE {
            get {
                return ResourceManager.GetString("WEAPON_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Website-URL ähnelt.
        /// </summary>
        internal static string WEBSITE_URL {
            get {
                return ResourceManager.GetString("WEBSITE_URL", resourceCulture);
            }
        }
    }
}
