//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPLauncherNET.Languages {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pt_BR() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAMPLauncherNET.Languages.pt-BR", typeof(pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///SAMPLauncher NET é um launcher para San Andreas Multiplayer.
        ///
        ///Este software é gratuito e licenciado com GPLv3.
        ///
        ///Este projeto é localizado em ähnelt.
        /// </summary>
        internal static string ABOUT_DESCRIPTION {
            get {
                return ResourceManager.GetString("ABOUT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Acknowledges limit ähnelt.
        /// </summary>
        internal static string ACKNOWLEDGES_LIMIT {
            get {
                return ResourceManager.GetString("ACKNOWLEDGES_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adicionar nova API ähnelt.
        /// </summary>
        internal static string ADD_NEW_API {
            get {
                return ResourceManager.GetString("ADD_NEW_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adicionar servidor aos favoritos ähnelt.
        /// </summary>
        internal static string ADD_SERVER_TO_FAVOURITES {
            get {
                return ResourceManager.GetString("ADD_SERVER_TO_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Já está em favoritos ähnelt.
        /// </summary>
        internal static string ALREADY_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("ALREADY_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anuncie o servidor ähnelt.
        /// </summary>
        internal static string ANNOUNCE {
            get {
                return ResourceManager.GetString("ANNOUNCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API ähnelt.
        /// </summary>
        internal static string API {
            get {
                return ResourceManager.GetString("API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API endpoint ähnelt.
        /// </summary>
        internal static string API_ENDPOINT {
            get {
                return ResourceManager.GetString("API_ENDPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Por favor especifique um endpoint válido para a API ähnelt.
        /// </summary>
        internal static string API_ENDPOINT_MISSING {
            get {
                return ResourceManager.GetString("API_ENDPOINT_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Faltando API endpoint ähnelt.
        /// </summary>
        internal static string API_ENDPOINT_MISSING_TITLE {
            get {
                return ResourceManager.GetString("API_ENDPOINT_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API nome ähnelt.
        /// </summary>
        internal static string API_NAME {
            get {
                return ResourceManager.GetString("API_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Por favor insira o nome da API. ähnelt.
        /// </summary>
        internal static string API_NAME_MISSING {
            get {
                return ResourceManager.GetString("API_NAME_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Faltando o nome da API ähnelt.
        /// </summary>
        internal static string API_NAME_MISSING_TITLE {
            get {
                return ResourceManager.GetString("API_NAME_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API tipo ähnelt.
        /// </summary>
        internal static string API_TYPE {
            get {
                return ResourceManager.GetString("API_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Por favor selecione o tipo da API. ähnelt.
        /// </summary>
        internal static string API_TYPE_MISSING {
            get {
                return ResourceManager.GetString("API_TYPE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Faltando o tipo da API ähnelt.
        /// </summary>
        internal static string API_TYPE_MISSING_TITLE {
            get {
                return ResourceManager.GetString("API_TYPE_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versão do assembly ähnelt.
        /// </summary>
        internal static string ASSEMBLY_VERSION {
            get {
                return ResourceManager.GetString("ASSEMBLY_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audio message off ähnelt.
        /// </summary>
        internal static string AUDIO_MESSAGE_OFF {
            get {
                return ResourceManager.GetString("AUDIO_MESSAGE_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audio proxy off ähnelt.
        /// </summary>
        internal static string AUDIO_PROXY_OFF {
            get {
                return ResourceManager.GetString("AUDIO_PROXY_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bind IP address ähnelt.
        /// </summary>
        internal static string BIND {
            get {
                return ResourceManager.GetString("BIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancelar ähnelt.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Habilitar chat logging ähnelt.
        /// </summary>
        internal static string CHAT_LOGGING {
            get {
                return ResourceManager.GetString("CHAT_LOGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cidade ähnelt.
        /// </summary>
        internal static string CITY {
            get {
                return ResourceManager.GetString("CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fechar quando abrir ähnelt.
        /// </summary>
        internal static string CLOSE_WHEN_LAUNCHED {
            get {
                return ResourceManager.GetString("CLOSE_WHEN_LAUNCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conectar ähnelt.
        /// </summary>
        internal static string CONNECT {
            get {
                return ResourceManager.GetString("CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conectar agora! ähnelt.
        /// </summary>
        internal static string CONNECT_NOW {
            get {
                return ResourceManager.GetString("CONNECT_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Conectar ähnelt.
        /// </summary>
        internal static string CONNECT_TITLE {
            get {
                return ResourceManager.GetString("CONNECT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conectar no endereço ähnelt.
        /// </summary>
        internal static string CONNECT_TO_ADDRESS {
            get {
                return ResourceManager.GetString("CONNECT_TO_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Conectar no endereço ähnelt.
        /// </summary>
        internal static string CONNECT_TO_ADDRESS_TITLE {
            get {
                return ResourceManager.GetString("CONNECT_TO_ADDRESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conectar no servidor de testes ähnelt.
        /// </summary>
        internal static string CONNECT_TO_TEST_SERVER {
            get {
                return ResourceManager.GetString("CONNECT_TO_TEST_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conectar com a RCON ähnelt.
        /// </summary>
        internal static string CONNECT_WITH_RCON {
            get {
                return ResourceManager.GetString("CONNECT_WITH_RCON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Permitir cookies de conexão ähnelt.
        /// </summary>
        internal static string CONNECTION_COOKIES {
            get {
                return ResourceManager.GetString("CONNECTION_COOKIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection seed time ähnelt.
        /// </summary>
        internal static string CONNECTION_SEED_TIME {
            get {
                return ResourceManager.GetString("CONNECTION_SEED_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Habilitar cookie logging ähnelt.
        /// </summary>
        internal static string COOKIE_LOGGING {
            get {
                return ResourceManager.GetString("COOKIE_LOGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pais ähnelt.
        /// </summary>
        internal static string COUNTRY {
            get {
                return ResourceManager.GetString("COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log de consultas do banco de dados ähnelt.
        /// </summary>
        internal static string DATABASE_LOG_QUERIES {
            get {
                return ResourceManager.GetString("DATABASE_LOG_QUERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Habilitar logging do banco de dados ähnelt.
        /// </summary>
        internal static string DATABASE_LOGGING {
            get {
                return ResourceManager.GetString("DATABASE_LOGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modo de depuração ähnelt.
        /// </summary>
        internal static string DEBUG_MODE {
            get {
                return ResourceManager.GetString("DEBUG_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Você realmente deseja deletar as imagens selecionadas? ähnelt.
        /// </summary>
        internal static string DELETE_SELECTED_IMAGES {
            get {
                return ResourceManager.GetString("DELETE_SELECTED_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deletar imagens selecionadas ähnelt.
        /// </summary>
        internal static string DELETE_SELECTED_IMAGES_TITLE {
            get {
                return ResourceManager.GetString("DELETE_SELECTED_IMAGES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ferramentas do desenvolvedor ähnelt.
        /// </summary>
        internal static string DEVELOPER_TOOLS {
            get {
                return ResourceManager.GetString("DEVELOPER_TOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Configuração das ferramentas do desenvolvedor ähnelt.
        /// </summary>
        internal static string DEVELOPER_TOOLS_CONFIGURATION_TITLE {
            get {
                return ResourceManager.GetString("DEVELOPER_TOOLS_CONFIGURATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diretório de desenvolvimento ähnelt.
        /// </summary>
        internal static string DEVELOPMENT_DIRECTORY {
            get {
                return ResourceManager.GetString("DEVELOPMENT_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Direct to screen textdraw render method (slow) ähnelt.
        /// </summary>
        internal static string DIRECT_MODE {
            get {
                return ResourceManager.GetString("DIRECT_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Desabilitar movimento da cabeça ähnelt.
        /// </summary>
        internal static string DISABLE_HEAD_MOVE {
            get {
                return ResourceManager.GetString("DISABLE_HEAD_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holandês (Nederlands) ähnelt.
        /// </summary>
        internal static string DUTCH {
            get {
                return ResourceManager.GetString("DUTCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Editar API ähnelt.
        /// </summary>
        internal static string EDIT_API_TITLE {
            get {
                return ResourceManager.GetString("EDIT_API_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Editar API selecionada ähnelt.
        /// </summary>
        internal static string EDIT_SELECTED_API {
            get {
                return ResourceManager.GetString("EDIT_SELECTED_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inglês (English) ähnelt.
        /// </summary>
        internal static string ENGLISH {
            get {
                return ResourceManager.GetString("ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Errr ähnelt.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Informações extendidas do servidor ähnelt.
        /// </summary>
        internal static string EXTENDED_SERVER_INFORMATION_TITLE {
            get {
                return ResourceManager.GetString("EXTENDED_SERVER_INFORMATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Por favor selecione uma lista de favoritos ähnelt.
        /// </summary>
        internal static string FAVOURITE_LIST_NOT_SELECTED {
            get {
                return ResourceManager.GetString("FAVOURITE_LIST_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lista de favoritos não selecionada ähnelt.
        /// </summary>
        internal static string FAVOURITE_LIST_NOT_SELECTED_TITLE {
            get {
                return ResourceManager.GetString("FAVOURITE_LIST_NOT_SELECTED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versão do arquivo ähnelt.
        /// </summary>
        internal static string FILE_VERSION {
            get {
                return ResourceManager.GetString("FILE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filtrar hostname ähnelt.
        /// </summary>
        internal static string FILTER_HOSTNAME {
            get {
                return ResourceManager.GetString("FILTER_HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filtrar IP e porta ähnelt.
        /// </summary>
        internal static string FILTER_IP_AND_PORT {
            get {
                return ResourceManager.GetString("FILTER_IP_AND_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filtrar lingua ähnelt.
        /// </summary>
        internal static string FILTER_LANGUAGE {
            get {
                return ResourceManager.GetString("FILTER_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filtrar modo ähnelt.
        /// </summary>
        internal static string FILTER_MODE {
            get {
                return ResourceManager.GetString("FILTER_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filterscripts ähnelt.
        /// </summary>
        internal static string FILTERSCRIPTS {
            get {
                return ResourceManager.GetString("FILTERSCRIPTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font-face ähnelt.
        /// </summary>
        internal static string FONT_FACE {
            get {
                return ResourceManager.GetString("FONT_FACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Espessura da fonte ähnelt.
        /// </summary>
        internal static string FONT_WEIGHT {
            get {
                return ResourceManager.GetString("FONT_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Limite de FPS ähnelt.
        /// </summary>
        internal static string FPS_LIMIT {
            get {
                return ResourceManager.GetString("FPS_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Galeria ähnelt.
        /// </summary>
        internal static string GALLERY {
            get {
                return ResourceManager.GetString("GALLERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gamemode ähnelt.
        /// </summary>
        internal static string GAMEMODE {
            get {
                return ResourceManager.GetString("GAMEMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gamemode text ähnelt.
        /// </summary>
        internal static string GAMEMODE_TEXT {
            get {
                return ResourceManager.GetString("GAMEMODE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gamemodes ähnelt.
        /// </summary>
        internal static string GAMEMODES {
            get {
                return ResourceManager.GetString("GAMEMODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Georgiano (ქართული) ähnelt.
        /// </summary>
        internal static string GEORGIAN {
            get {
                return ResourceManager.GetString("GEORGIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alemão (Deutsch) ähnelt.
        /// </summary>
        internal static string GERMAN {
            get {
                return ResourceManager.GetString("GERMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projeto github SAMPLauncherNET ähnelt.
        /// </summary>
        internal static string GITHUB_PROJECT {
            get {
                return ResourceManager.GetString("GITHUB_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Host e porta ähnelt.
        /// </summary>
        internal static string HOST_AND_PORT {
            get {
                return ResourceManager.GetString("HOST_AND_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hostname ähnelt.
        /// </summary>
        internal static string HOSTNAME {
            get {
                return ResourceManager.GetString("HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable IME (Input Method Editor) ähnelt.
        /// </summary>
        internal static string IME {
            get {
                return ResourceManager.GetString("IME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In car tick rate ähnelt.
        /// </summary>
        internal static string IN_CAR_RATE {
            get {
                return ResourceManager.GetString("IN_CAR_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input error ähnelt.
        /// </summary>
        internal static string INPUT_ERROR {
            get {
                return ResourceManager.GetString("INPUT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insira o filtro aqui... ähnelt.
        /// </summary>
        internal static string INSERT_FILTER_HERE {
            get {
                return ResourceManager.GetString("INSERT_FILTER_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insira a senha RCON aqui... ähnelt.
        /// </summary>
        internal static string INSERT_RCON_PASSWORD_HERE {
            get {
                return ResourceManager.GetString("INSERT_RCON_PASSWORD_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insira a senha do servidor aqui... ähnelt.
        /// </summary>
        internal static string INSERT_SERVER_PASSWORD_HERE {
            get {
                return ResourceManager.GetString("INSERT_SERVER_PASSWORD_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insira o nome do jogador aqui... ähnelt.
        /// </summary>
        internal static string INSERT_USERNAME_HERE {
            get {
                return ResourceManager.GetString("INSERT_USERNAME_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP e port ähnelt.
        /// </summary>
        internal static string IP_AND_PORT {
            get {
                return ResourceManager.GetString("IP_AND_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lag compensation mode ähnelt.
        /// </summary>
        internal static string LAG_COMPENSATION_MODE {
            get {
                return ResourceManager.GetString("LAG_COMPENSATION_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LAN mode ähnelt.
        /// </summary>
        internal static string LAN_MODE {
            get {
                return ResourceManager.GetString("LAN_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last chatlog ähnelt.
        /// </summary>
        internal static string LAST_CHATLOG {
            get {
                return ResourceManager.GetString("LAST_CHATLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latitude e longitude ähnelt.
        /// </summary>
        internal static string LATITUDE_LONGITUDE {
            get {
                return ResourceManager.GetString("LATITUDE_LONGITUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iniciar modo de depuração ähnelt.
        /// </summary>
        internal static string LAUNCH_DEBUG_MODE {
            get {
                return ResourceManager.GetString("LAUNCH_DEBUG_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iniciar singleplayer ähnelt.
        /// </summary>
        internal static string LAUNCH_SINGLEPLAYER {
            get {
                return ResourceManager.GetString("LAUNCH_SINGLEPLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Launcher ähnelt.
        /// </summary>
        internal static string LAUNCHER_TITLE {
            get {
                return ResourceManager.GetString("LAUNCHER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log queries ähnelt.
        /// </summary>
        internal static string LOG_QUERIES {
            get {
                return ResourceManager.GetString("LOG_QUERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log time format ähnelt.
        /// </summary>
        internal static string LOG_TIME_FORMAT {
            get {
                return ResourceManager.GetString("LOG_TIME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Map name ähnelt.
        /// </summary>
        internal static string MAP_NAME {
            get {
                return ResourceManager.GetString("MAP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximal NPCs ähnelt.
        /// </summary>
        internal static string MAXIMAL_NPCS {
            get {
                return ResourceManager.GetString("MAXIMAL_NPCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximal players ähnelt.
        /// </summary>
        internal static string MAXIMAL_PLAYERS {
            get {
                return ResourceManager.GetString("MAXIMAL_PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message hole limit ähnelt.
        /// </summary>
        internal static string MESSAGE_HOLE_LIMIT {
            get {
                return ResourceManager.GetString("MESSAGE_HOLE_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messages limit ähnelt.
        /// </summary>
        internal static string MESSAGES_LIMIT {
            get {
                return ResourceManager.GetString("MESSAGES_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Metro code ähnelt.
        /// </summary>
        internal static string METRO_CODE {
            get {
                return ResourceManager.GetString("METRO_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum connection time ähnelt.
        /// </summary>
        internal static string MINIMUM_CONNECTION_TIME {
            get {
                return ResourceManager.GetString("MINIMUM_CONNECTION_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multi core ähnelt.
        /// </summary>
        internal static string MULTI_CORE {
            get {
                return ResourceManager.GetString("MULTI_CORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Precisa de ajuda? Visite o fórum SA:MP... ähnelt.
        /// </summary>
        internal static string NEED_HELP_FORUMS {
            get {
                return ResourceManager.GetString("NEED_HELP_FORUMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Adiconar nova API ähnelt.
        /// </summary>
        internal static string NEW_API_TITLE {
            get {
                return ResourceManager.GetString("NEW_API_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No chatlog found... ähnelt.
        /// </summary>
        internal static string NO_CHATLOG_FOUND {
            get {
                return ResourceManager.GetString("NO_CHATLOG_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are no favourite lists defined. To define a new favourite list, select the &quot;API&quot; tab and create a new favourite list or restore the default entries. ähnelt.
        /// </summary>
        internal static string NO_FAVOURITES {
            get {
                return ResourceManager.GetString("NO_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No favourite lists ähnelt.
        /// </summary>
        internal static string NO_FAVOURITES_TITLE {
            get {
                return ResourceManager.GetString("NO_FAVOURITES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No nametag status ähnelt.
        /// </summary>
        internal static string NO_NAMETAG_STATUS {
            get {
                return ResourceManager.GetString("NO_NAMETAG_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No sign ähnelt.
        /// </summary>
        internal static string NO_SIGN {
            get {
                return ResourceManager.GetString("NO_SIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not in favourites ähnelt.
        /// </summary>
        internal static string NOT_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("NOT_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On foot tick rate ähnelt.
        /// </summary>
        internal static string ON_FOOT_RATE {
            get {
                return ResourceManager.GetString("ON_FOOT_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abrir diretório ähnelt.
        /// </summary>
        internal static string OPEN_DIRECTORY {
            get {
                return ResourceManager.GetString("OPEN_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abrir no navegador ähnelt.
        /// </summary>
        internal static string OPEN_IN_EXPLORER {
            get {
                return ResourceManager.GetString("OPEN_IN_EXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opções ähnelt.
        /// </summary>
        internal static string OPTIONS {
            get {
                return ResourceManager.GetString("OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Options ähnelt.
        /// </summary>
        internal static string OPTIONS_TITLE {
            get {
                return ResourceManager.GetString("OPTIONS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page size ähnelt.
        /// </summary>
        internal static string PAGE_SIZE {
            get {
                return ResourceManager.GetString("PAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Senha ähnelt.
        /// </summary>
        internal static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ping ähnelt.
        /// </summary>
        internal static string PING {
            get {
                return ResourceManager.GetString("PING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player time out ähnelt.
        /// </summary>
        internal static string PLAYER_TIME_OUT {
            get {
                return ResourceManager.GetString("PLAYER_TIME_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Players ähnelt.
        /// </summary>
        internal static string PLAYERS {
            get {
                return ResourceManager.GetString("PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please type in an username. ähnelt.
        /// </summary>
        internal static string PLEASE_TYPE_IN_USERNAME {
            get {
                return ResourceManager.GetString("PLEASE_TYPE_IN_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugins ähnelt.
        /// </summary>
        internal static string PLUGINS {
            get {
                return ResourceManager.GetString("PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Port ähnelt.
        /// </summary>
        internal static string PORT {
            get {
                return ResourceManager.GetString("PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Português ähnelt.
        /// </summary>
        internal static string PORTUGUESE {
            get {
                return ResourceManager.GetString("PORTUGUESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Português de Brasil ähnelt.
        /// </summary>
        internal static string PORTUGUESE_BRAZIL {
            get {
                return ResourceManager.GetString("PORTUGUESE_BRAZIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Product version ähnelt.
        /// </summary>
        internal static string PRODUCT_VERSION {
            get {
                return ResourceManager.GetString("PRODUCT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable query ähnelt.
        /// </summary>
        internal static string QUERY {
            get {
                return ResourceManager.GetString("QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable RCON ähnelt.
        /// </summary>
        internal static string RCON {
            get {
                return ResourceManager.GetString("RCON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RCON password ähnelt.
        /// </summary>
        internal static string RCON_PASSWORD {
            get {
                return ResourceManager.GetString("RCON_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - RCON password ähnelt.
        /// </summary>
        internal static string RCON_PASSWORD_TITLE {
            get {
                return ResourceManager.GetString("RCON_PASSWORD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Region ähnelt.
        /// </summary>
        internal static string REGION {
            get {
                return ResourceManager.GetString("REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to remove the selected API? ähnelt.
        /// </summary>
        internal static string REMOVE_API {
            get {
                return ResourceManager.GetString("REMOVE_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove selected API ähnelt.
        /// </summary>
        internal static string REMOVE_API_TITLE {
            get {
                return ResourceManager.GetString("REMOVE_API_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove selected API ähnelt.
        /// </summary>
        internal static string REMOVE_SELECTED_API {
            get {
                return ResourceManager.GetString("REMOVE_SELECTED_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to remove this server from your favourites? ähnelt.
        /// </summary>
        internal static string REMOVE_SERVER_FROM_FAVOURITES {
            get {
                return ResourceManager.GetString("REMOVE_SERVER_FROM_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove server from favourites ähnelt.
        /// </summary>
        internal static string REMOVE_SERVER_FROM_FAVOURITES_TITLE {
            get {
                return ResourceManager.GetString("REMOVE_SERVER_FROM_FAVOURITES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to revert the API list to default? ähnelt.
        /// </summary>
        internal static string REVERT_API_LIST {
            get {
                return ResourceManager.GetString("REVERT_API_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Revert API list ähnelt.
        /// </summary>
        internal static string REVERT_API_LIST_TITLE {
            get {
                return ResourceManager.GetString("REVERT_API_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Revert config ähnelt.
        /// </summary>
        internal static string REVERT_CONFIG {
            get {
                return ResourceManager.GetString("REVERT_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Russian (Русский) ähnelt.
        /// </summary>
        internal static string RUSSIAN {
            get {
                return ResourceManager.GetString("RUSSIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saved positions ähnelt.
        /// </summary>
        internal static string SAVED_POSITIONS {
            get {
                return ResourceManager.GetString("SAVED_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search on... ähnelt.
        /// </summary>
        internal static string SEARCH_ON {
            get {
                return ResourceManager.GetString("SEARCH_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bing ähnelt.
        /// </summary>
        internal static string SEARCH_ON_BING {
            get {
                return ResourceManager.GetString("SEARCH_ON_BING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DuckDuckGo ähnelt.
        /// </summary>
        internal static string SEARCH_ON_DUCK_DUCK_GO {
            get {
                return ResourceManager.GetString("SEARCH_ON_DUCK_DUCK_GO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Google ähnelt.
        /// </summary>
        internal static string SEARCH_ON_GOOGLE {
            get {
                return ResourceManager.GetString("SEARCH_ON_GOOGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yahoo ähnelt.
        /// </summary>
        internal static string SEARCH_ON_YAHOO {
            get {
                return ResourceManager.GetString("SEARCH_ON_YAHOO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yandex ähnelt.
        /// </summary>
        internal static string SEARCH_ON_YANDEX {
            get {
                return ResourceManager.GetString("SEARCH_ON_YANDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die YouTube ähnelt.
        /// </summary>
        internal static string SEARCH_ON_YOU_TUBE {
            get {
                return ResourceManager.GetString("SEARCH_ON_YOU_TUBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a server list ähnelt.
        /// </summary>
        internal static string SELECT_API {
            get {
                return ResourceManager.GetString("SELECT_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Select favourite list ähnelt.
        /// </summary>
        internal static string SELECT_FAVOURITE_LIST_TITLE {
            get {
                return ResourceManager.GetString("SELECT_FAVOURITE_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select favourites list ähnelt.
        /// </summary>
        internal static string SELECT_FAVOURITES_LIST {
            get {
                return ResourceManager.GetString("SELECT_FAVOURITES_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select language ähnelt.
        /// </summary>
        internal static string SELECT_LANGUAGE {
            get {
                return ResourceManager.GetString("SELECT_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select server list ähnelt.
        /// </summary>
        internal static string SELECT_SERVER_LIST {
            get {
                return ResourceManager.GetString("SELECT_SERVER_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This server is already in your favourites. ähnelt.
        /// </summary>
        internal static string SERVER_ALREADY_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("SERVER_ALREADY_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This server is not in your favourites. ähnelt.
        /// </summary>
        internal static string SERVER_NOT_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("SERVER_NOT_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server password ähnelt.
        /// </summary>
        internal static string SERVER_PASSWORD {
            get {
                return ResourceManager.GetString("SERVER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server password field is empty.
        ///
        ///Do you want to continue? ähnelt.
        /// </summary>
        internal static string SERVER_PASSWORD_FIELD_IS_EMPTY {
            get {
                return ResourceManager.GetString("SERVER_PASSWORD_FIELD_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server password field is empty ähnelt.
        /// </summary>
        internal static string SERVER_PASSWORD_FIELD_IS_EMPTY_TITLE {
            get {
                return ResourceManager.GetString("SERVER_PASSWORD_FIELD_IS_EMPTY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Servers ähnelt.
        /// </summary>
        internal static string SERVERS {
            get {
                return ResourceManager.GetString("SERVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server filter ähnelt.
        /// </summary>
        internal static string SERVERS_FILTER {
            get {
                return ResourceManager.GetString("SERVERS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show additional configurations ähnelt.
        /// </summary>
        internal static string SHOW_ADDITIONAL_CONFIGURATIONS {
            get {
                return ResourceManager.GetString("SHOW_ADDITIONAL_CONFIGURATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extended server information ähnelt.
        /// </summary>
        internal static string SHOW_EXTENDED_SERVER_INFORMATION {
            get {
                return ResourceManager.GetString("SHOW_EXTENDED_SERVER_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favourites ähnelt.
        /// </summary>
        internal static string SHOW_FAVOURITES {
            get {
                return ResourceManager.GetString("SHOW_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show gallery... ähnelt.
        /// </summary>
        internal static string SHOW_GALLERY {
            get {
                return ResourceManager.GetString("SHOW_GALLERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show in Google Maps ähnelt.
        /// </summary>
        internal static string SHOW_IN_GOOGLE_MAPS {
            get {
                return ResourceManager.GetString("SHOW_IN_GOOGLE_MAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show in OpenStreetMap ähnelt.
        /// </summary>
        internal static string SHOW_IN_OPEN_STREET_MAP {
            get {
                return ResourceManager.GetString("SHOW_IN_OPEN_STREET_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show last chatlog... ähnelt.
        /// </summary>
        internal static string SHOW_LAST_CHATLOG {
            get {
                return ResourceManager.GetString("SHOW_LAST_CHATLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legacy favourites ähnelt.
        /// </summary>
        internal static string SHOW_LEGACY_FAVOURITES {
            get {
                return ResourceManager.GetString("SHOW_LEGACY_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hosted list ähnelt.
        /// </summary>
        internal static string SHOW_LEGACY_HOSTED_LIST {
            get {
                return ResourceManager.GetString("SHOW_LEGACY_HOSTED_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Master list ähnelt.
        /// </summary>
        internal static string SHOW_LEGACY_MASTER_LIST {
            get {
                return ResourceManager.GetString("SHOW_LEGACY_MASTER_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sleep time ähnelt.
        /// </summary>
        internal static string SLEEP {
            get {
                return ResourceManager.GetString("SLEEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start server ähnelt.
        /// </summary>
        internal static string START_SERVER {
            get {
                return ResourceManager.GetString("START_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop server ähnelt.
        /// </summary>
        internal static string STOP_SERVER {
            get {
                return ResourceManager.GetString("STOP_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stream distance ähnelt.
        /// </summary>
        internal static string STREAM_DISTANCE {
            get {
                return ResourceManager.GetString("STREAM_DISTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stream rate ähnelt.
        /// </summary>
        internal static string STREAM_RATE {
            get {
                return ResourceManager.GetString("STREAM_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t save username ähnelt.
        /// </summary>
        internal static string TEMPORARY_USERNAME {
            get {
                return ResourceManager.GetString("TEMPORARY_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time zone ähnelt.
        /// </summary>
        internal static string TIME_ZONE {
            get {
                return ResourceManager.GetString("TIME_ZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timestamp ähnelt.
        /// </summary>
        internal static string TIMESTAMP {
            get {
                return ResourceManager.GetString("TIMESTAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        internal static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visit website ähnelt.
        /// </summary>
        internal static string VISIT_WEBSITE {
            get {
                return ResourceManager.GetString("VISIT_WEBSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to visit this website? ähnelt.
        /// </summary>
        internal static string VISIT_WEBSITE_MESSAGE {
            get {
                return ResourceManager.GetString("VISIT_WEBSITE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visit ähnelt.
        /// </summary>
        internal static string VISIT_WEBSITE_TITLE {
            get {
                return ResourceManager.GetString("VISIT_WEBSITE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weapon rate ähnelt.
        /// </summary>
        internal static string WEAPON_RATE {
            get {
                return ResourceManager.GetString("WEAPON_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Website URL ähnelt.
        /// </summary>
        internal static string WEBSITE_URL {
            get {
                return ResourceManager.GetString("WEBSITE_URL", resourceCulture);
            }
        }
    }
}
