//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPLauncherNET.Languages {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pt_PT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pt_PT() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAMPLauncherNET.Languages.pt-PT", typeof(pt_PT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sobre ähnelt.
        /// </summary>
        internal static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///SAMPLauncher NET is a launcher for San Andreas Multiplayer.
        ///
        ///This software is all time free and licensed with GPLv3.
        ///
        ///This project is located at ähnelt.
        /// </summary>
        internal static string ABOUT_DESCRIPTION {
            get {
                return ResourceManager.GetString("ABOUT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Limite de ACKS ähnelt.
        /// </summary>
        internal static string ACKNOWLEDGES_LIMIT {
            get {
                return ResourceManager.GetString("ACKNOWLEDGES_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Marcar como Favorito ähnelt.
        /// </summary>
        internal static string ADD_ADDRESS_TO_FAVOURITE_LIST {
            get {
                return ResourceManager.GetString("ADD_ADDRESS_TO_FAVOURITE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Marcar como Favorito ähnelt.
        /// </summary>
        internal static string ADD_ADDRESS_TO_FAVOURITE_LIST_TITLE {
            get {
                return ResourceManager.GetString("ADD_ADDRESS_TO_FAVOURITE_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adicionar nova API ähnelt.
        /// </summary>
        internal static string ADD_NEW_API {
            get {
                return ResourceManager.GetString("ADD_NEW_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Marcar como Favotiro ähnelt.
        /// </summary>
        internal static string ADD_SERVER_TO_FAVOURITES {
            get {
                return ResourceManager.GetString("ADD_SERVER_TO_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Já marcado como Favorito ähnelt.
        /// </summary>
        internal static string ALREADY_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("ALREADY_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anunciar servidor ähnelt.
        /// </summary>
        internal static string ANNOUNCE {
            get {
                return ResourceManager.GetString("ANNOUNCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API ähnelt.
        /// </summary>
        internal static string API {
            get {
                return ResourceManager.GetString("API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API endpoint: ähnelt.
        /// </summary>
        internal static string API_ENDPOINT {
            get {
                return ResourceManager.GetString("API_ENDPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Por favor especifica um endpoint válido para a API ähnelt.
        /// </summary>
        internal static string API_ENDPOINT_MISSING {
            get {
                return ResourceManager.GetString("API_ENDPOINT_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Endpoint da API em falta ähnelt.
        /// </summary>
        internal static string API_ENDPOINT_MISSING_TITLE {
            get {
                return ResourceManager.GetString("API_ENDPOINT_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nome da API: ähnelt.
        /// </summary>
        internal static string API_NAME {
            get {
                return ResourceManager.GetString("API_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Por favor insere um nome para a API ähnelt.
        /// </summary>
        internal static string API_NAME_MISSING {
            get {
                return ResourceManager.GetString("API_NAME_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nome da API em falta ähnelt.
        /// </summary>
        internal static string API_NAME_MISSING_TITLE {
            get {
                return ResourceManager.GetString("API_NAME_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tipo de API: ähnelt.
        /// </summary>
        internal static string API_TYPE {
            get {
                return ResourceManager.GetString("API_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Escolhe o tipo da API ähnelt.
        /// </summary>
        internal static string API_TYPE_MISSING {
            get {
                return ResourceManager.GetString("API_TYPE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tipo da API em falta ähnelt.
        /// </summary>
        internal static string API_TYPE_MISSING_TITLE {
            get {
                return ResourceManager.GetString("API_TYPE_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versão da Assembly ähnelt.
        /// </summary>
        internal static string ASSEMBLY_VERSION {
            get {
                return ResourceManager.GetString("ASSEMBLY_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messagem de áudio activa ähnelt.
        /// </summary>
        internal static string AUDIO_MESSAGE_OFF {
            get {
                return ResourceManager.GetString("AUDIO_MESSAGE_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messagem de áudio desactiva ähnelt.
        /// </summary>
        internal static string AUDIO_PROXY_OFF {
            get {
                return ResourceManager.GetString("AUDIO_PROXY_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bind IP address ähnelt.
        /// </summary>
        internal static string BIND {
            get {
                return ResourceManager.GetString("BIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancelar ähnelt.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Queres mesmo cancelar o download? ähnelt.
        /// </summary>
        internal static string CANCEL_DOWNLOAD {
            get {
                return ResourceManager.GetString("CANCEL_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancelar download ähnelt.
        /// </summary>
        internal static string CANCEL_DOWNLOAD_TITLE {
            get {
                return ResourceManager.GetString("CANCEL_DOWNLOAD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activar gravação do chat ähnelt.
        /// </summary>
        internal static string CHAT_LOGGING {
            get {
                return ResourceManager.GetString("CHAT_LOGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cidade ähnelt.
        /// </summary>
        internal static string CITY {
            get {
                return ResourceManager.GetString("CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fechar depois de ligar... ähnelt.
        /// </summary>
        internal static string CLOSE_WHEN_LAUNCHED {
            get {
                return ResourceManager.GetString("CLOSE_WHEN_LAUNCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ligar ähnelt.
        /// </summary>
        internal static string CONNECT {
            get {
                return ResourceManager.GetString("CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ligar agora! ähnelt.
        /// </summary>
        internal static string CONNECT_NOW {
            get {
                return ResourceManager.GetString("CONNECT_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Ligar ähnelt.
        /// </summary>
        internal static string CONNECT_TITLE {
            get {
                return ResourceManager.GetString("CONNECT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ligar Directamente ähnelt.
        /// </summary>
        internal static string CONNECT_TO_ADDRESS {
            get {
                return ResourceManager.GetString("CONNECT_TO_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Ligar diretamente ähnelt.
        /// </summary>
        internal static string CONNECT_TO_ADDRESS_TITLE {
            get {
                return ResourceManager.GetString("CONNECT_TO_ADDRESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ligar ao Servidor ähnelt.
        /// </summary>
        internal static string CONNECT_TO_TEST_SERVER {
            get {
                return ResourceManager.GetString("CONNECT_TO_TEST_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ligar com password RCON ähnelt.
        /// </summary>
        internal static string CONNECT_WITH_RCON {
            get {
                return ResourceManager.GetString("CONNECT_WITH_RCON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Autorizar cookies de ligação ähnelt.
        /// </summary>
        internal static string CONNECTION_COOKIES {
            get {
                return ResourceManager.GetString("CONNECTION_COOKIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection seed time ähnelt.
        /// </summary>
        internal static string CONNECTION_SEED_TIME {
            get {
                return ResourceManager.GetString("CONNECTION_SEED_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activar gravação de cookies ähnelt.
        /// </summary>
        internal static string COOKIE_LOGGING {
            get {
                return ResourceManager.GetString("COOKIE_LOGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die País ähnelt.
        /// </summary>
        internal static string COUNTRY {
            get {
                return ResourceManager.GetString("COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database log queries ähnelt.
        /// </summary>
        internal static string DATABASE_LOG_QUERIES {
            get {
                return ResourceManager.GetString("DATABASE_LOG_QUERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activar gravação da base de dados ähnelt.
        /// </summary>
        internal static string DATABASE_LOGGING {
            get {
                return ResourceManager.GetString("DATABASE_LOGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modo de depuração ähnelt.
        /// </summary>
        internal static string DEBUG_MODE {
            get {
                return ResourceManager.GetString("DEBUG_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Queres mesmo eliminar as imagens selecionadas? ähnelt.
        /// </summary>
        internal static string DELETE_SELECTED_IMAGES {
            get {
                return ResourceManager.GetString("DELETE_SELECTED_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eliminar imagens selecionadas ähnelt.
        /// </summary>
        internal static string DELETE_SELECTED_IMAGES_TITLE {
            get {
                return ResourceManager.GetString("DELETE_SELECTED_IMAGES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ferramentas de Desenvolvimento ähnelt.
        /// </summary>
        internal static string DEVELOPER_TOOLS {
            get {
                return ResourceManager.GetString("DEVELOPER_TOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Configuração das Ferramentas de Desenvolvimento ähnelt.
        /// </summary>
        internal static string DEVELOPER_TOOLS_CONFIGURATION_TITLE {
            get {
                return ResourceManager.GetString("DEVELOPER_TOOLS_CONFIGURATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pasta de Desenvolvimento ähnelt.
        /// </summary>
        internal static string DEVELOPMENT_DIRECTORY {
            get {
                return ResourceManager.GetString("DEVELOPMENT_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Direct to screen textdraw render method (slow) ähnelt.
        /// </summary>
        internal static string DIRECT_MODE {
            get {
                return ResourceManager.GetString("DIRECT_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Desactivar movimento da cabeça ähnelt.
        /// </summary>
        internal static string DISABLE_HEAD_MOVE {
            get {
                return ResourceManager.GetString("DISABLE_HEAD_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download falhado ähnelt.
        /// </summary>
        internal static string DOWNLOAD_FAILED_TITLE {
            get {
                return ResourceManager.GetString("DOWNLOAD_FAILED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A efectuar o download ähnelt.
        /// </summary>
        internal static string DOWNLOAD_PROGRESS {
            get {
                return ResourceManager.GetString("DOWNLOAD_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Progresso do download ähnelt.
        /// </summary>
        internal static string DOWNLOAD_PROGRESS_TITLE {
            get {
                return ResourceManager.GetString("DOWNLOAD_PROGRESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dutch (Nederlands) ähnelt.
        /// </summary>
        internal static string DUTCH {
            get {
                return ResourceManager.GetString("DUTCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Editar API ähnelt.
        /// </summary>
        internal static string EDIT_API_TITLE {
            get {
                return ResourceManager.GetString("EDIT_API_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Editar API selecionada ähnelt.
        /// </summary>
        internal static string EDIT_SELECTED_API {
            get {
                return ResourceManager.GetString("EDIT_SELECTED_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inglês ähnelt.
        /// </summary>
        internal static string ENGLISH {
            get {
                return ResourceManager.GetString("ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erro ähnelt.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Informação adicional do servidor ähnelt.
        /// </summary>
        internal static string EXTENDED_SERVER_INFORMATION_TITLE {
            get {
                return ResourceManager.GetString("EXTENDED_SERVER_INFORMATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Por favor seleciona uma lista de favoritos ähnelt.
        /// </summary>
        internal static string FAVOURITE_LIST_NOT_SELECTED {
            get {
                return ResourceManager.GetString("FAVOURITE_LIST_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lista de favoritos não selecionada ähnelt.
        /// </summary>
        internal static string FAVOURITE_LIST_NOT_SELECTED_TITLE {
            get {
                return ResourceManager.GetString("FAVOURITE_LIST_NOT_SELECTED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versão de ficheiro ähnelt.
        /// </summary>
        internal static string FILE_VERSION {
            get {
                return ResourceManager.GetString("FILE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nome ähnelt.
        /// </summary>
        internal static string FILTER_HOSTNAME {
            get {
                return ResourceManager.GetString("FILTER_HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP e Porta ähnelt.
        /// </summary>
        internal static string FILTER_IP_AND_PORT {
            get {
                return ResourceManager.GetString("FILTER_IP_AND_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Língua ähnelt.
        /// </summary>
        internal static string FILTER_LANGUAGE {
            get {
                return ResourceManager.GetString("FILTER_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gamemode ähnelt.
        /// </summary>
        internal static string FILTER_MODE {
            get {
                return ResourceManager.GetString("FILTER_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filterscripts ähnelt.
        /// </summary>
        internal static string FILTERSCRIPTS {
            get {
                return ResourceManager.GetString("FILTERSCRIPTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font-face ähnelt.
        /// </summary>
        internal static string FONT_FACE {
            get {
                return ResourceManager.GetString("FONT_FACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font-weight ähnelt.
        /// </summary>
        internal static string FONT_WEIGHT {
            get {
                return ResourceManager.GetString("FONT_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Limite de FPS ähnelt.
        /// </summary>
        internal static string FPS_LIMIT {
            get {
                return ResourceManager.GetString("FPS_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gamemode ähnelt.
        /// </summary>
        internal static string GAMEMODE {
            get {
                return ResourceManager.GetString("GAMEMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Texto do Gamemode ähnelt.
        /// </summary>
        internal static string GAMEMODE_TEXT {
            get {
                return ResourceManager.GetString("GAMEMODE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gamemodes ähnelt.
        /// </summary>
        internal static string GAMEMODES {
            get {
                return ResourceManager.GetString("GAMEMODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Georgian (ქართული) ähnelt.
        /// </summary>
        internal static string GEORGIAN {
            get {
                return ResourceManager.GetString("GEORGIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alemão (Deutsch) ähnelt.
        /// </summary>
        internal static string GERMAN {
            get {
                return ResourceManager.GetString("GERMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projecto do SAMPLauncherNET no Github ähnelt.
        /// </summary>
        internal static string GITHUB_PROJECT {
            get {
                return ResourceManager.GetString("GITHUB_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP/Host e Porta: ähnelt.
        /// </summary>
        internal static string HOST_AND_PORT {
            get {
                return ResourceManager.GetString("HOST_AND_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nome do Servidor ähnelt.
        /// </summary>
        internal static string HOSTNAME {
            get {
                return ResourceManager.GetString("HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable IME (Input Method Editor) ähnelt.
        /// </summary>
        internal static string IME {
            get {
                return ResourceManager.GetString("IME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In car tick rate ähnelt.
        /// </summary>
        internal static string IN_CAR_RATE {
            get {
                return ResourceManager.GetString("IN_CAR_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input error ähnelt.
        /// </summary>
        internal static string INPUT_ERROR {
            get {
                return ResourceManager.GetString("INPUT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert filter here... ähnelt.
        /// </summary>
        internal static string INSERT_FILTER_HERE {
            get {
                return ResourceManager.GetString("INSERT_FILTER_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert RCON password here... ähnelt.
        /// </summary>
        internal static string INSERT_RCON_PASSWORD_HERE {
            get {
                return ResourceManager.GetString("INSERT_RCON_PASSWORD_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert server password here... ähnelt.
        /// </summary>
        internal static string INSERT_SERVER_PASSWORD_HERE {
            get {
                return ResourceManager.GetString("INSERT_SERVER_PASSWORD_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert player name here... ähnelt.
        /// </summary>
        internal static string INSERT_USERNAME_HERE {
            get {
                return ResourceManager.GetString("INSERT_USERNAME_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Queres mesmo instalar {0}? ähnelt.
        /// </summary>
        internal static string INSTALL_VERSION {
            get {
                return ResourceManager.GetString("INSTALL_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versão ähnelt.
        /// </summary>
        internal static string INSTALL_VERSION_TITLE {
            get {
                return ResourceManager.GetString("INSTALL_VERSION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP e Porta ähnelt.
        /// </summary>
        internal static string IP_AND_PORT {
            get {
                return ResourceManager.GetString("IP_AND_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modo de compensação de lag ähnelt.
        /// </summary>
        internal static string LAG_COMPENSATION_MODE {
            get {
                return ResourceManager.GetString("LAG_COMPENSATION_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modo de LAN ähnelt.
        /// </summary>
        internal static string LAN_MODE {
            get {
                return ResourceManager.GetString("LAN_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Língua ähnelt.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latitude and longitude ähnelt.
        /// </summary>
        internal static string LATITUDE_LONGITUDE {
            get {
                return ResourceManager.GetString("LATITUDE_LONGITUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iniciar Modo de Depuração ähnelt.
        /// </summary>
        internal static string LAUNCH_DEBUG_MODE {
            get {
                return ResourceManager.GetString("LAUNCH_DEBUG_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iniciar Singleplayer ähnelt.
        /// </summary>
        internal static string LAUNCH_SINGLEPLAYER {
            get {
                return ResourceManager.GetString("LAUNCH_SINGLEPLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Launcher ähnelt.
        /// </summary>
        internal static string LAUNCHER_TITLE {
            get {
                return ResourceManager.GetString("LAUNCHER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log queries ähnelt.
        /// </summary>
        internal static string LOG_QUERIES {
            get {
                return ResourceManager.GetString("LOG_QUERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log time format ähnelt.
        /// </summary>
        internal static string LOG_TIME_FORMAT {
            get {
                return ResourceManager.GetString("LOG_TIME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nome do Mapa ähnelt.
        /// </summary>
        internal static string MAP_NAME {
            get {
                return ResourceManager.GetString("MAP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximal NPCs ähnelt.
        /// </summary>
        internal static string MAXIMAL_NPCS {
            get {
                return ResourceManager.GetString("MAXIMAL_NPCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximal players ähnelt.
        /// </summary>
        internal static string MAXIMAL_PLAYERS {
            get {
                return ResourceManager.GetString("MAXIMAL_PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mídia ähnelt.
        /// </summary>
        internal static string MEDIA {
            get {
                return ResourceManager.GetString("MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message hole limit ähnelt.
        /// </summary>
        internal static string MESSAGE_HOLE_LIMIT {
            get {
                return ResourceManager.GetString("MESSAGE_HOLE_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messages limit ähnelt.
        /// </summary>
        internal static string MESSAGES_LIMIT {
            get {
                return ResourceManager.GetString("MESSAGES_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Metro code ähnelt.
        /// </summary>
        internal static string METRO_CODE {
            get {
                return ResourceManager.GetString("METRO_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum connection time ähnelt.
        /// </summary>
        internal static string MINIMUM_CONNECTION_TIME {
            get {
                return ResourceManager.GetString("MINIMUM_CONNECTION_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multi core ähnelt.
        /// </summary>
        internal static string MULTI_CORE {
            get {
                return ResourceManager.GetString("MULTI_CORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Precisas de ajuda? Entra no forum do SA:MP... ähnelt.
        /// </summary>
        internal static string NEED_HELP_FORUMS {
            get {
                return ResourceManager.GetString("NEED_HELP_FORUMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Adicionar nova API ähnelt.
        /// </summary>
        internal static string NEW_API_TITLE {
            get {
                return ResourceManager.GetString("NEW_API_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please specify an address to add to your favourites list. ähnelt.
        /// </summary>
        internal static string NO_ADDRESS_SPECIFIED {
            get {
                return ResourceManager.GetString("NO_ADDRESS_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nenhum endereço especificado ähnelt.
        /// </summary>
        internal static string NO_ADDRESS_SPECIFIED_TITLE {
            get {
                return ResourceManager.GetString("NO_ADDRESS_SPECIFIED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No chatlog found... ähnelt.
        /// </summary>
        internal static string NO_CHATLOG_FOUND {
            get {
                return ResourceManager.GetString("NO_CHATLOG_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are no favourite lists defined. To define a new favourite list, select the &quot;API&quot; tab and create a new favourite list or restore the default entries. ähnelt.
        /// </summary>
        internal static string NO_FAVOURITES {
            get {
                return ResourceManager.GetString("NO_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No favourite lists ähnelt.
        /// </summary>
        internal static string NO_FAVOURITES_TITLE {
            get {
                return ResourceManager.GetString("NO_FAVOURITES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No nametag status ähnelt.
        /// </summary>
        internal static string NO_NAMETAG_STATUS {
            get {
                return ResourceManager.GetString("NO_NAMETAG_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No sign ähnelt.
        /// </summary>
        internal static string NO_SIGN {
            get {
                return ResourceManager.GetString("NO_SIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not in favourites ähnelt.
        /// </summary>
        internal static string NOT_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("NOT_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On foot tick rate ähnelt.
        /// </summary>
        internal static string ON_FOOT_RATE {
            get {
                return ResourceManager.GetString("ON_FOOT_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abrir Pasta ähnelt.
        /// </summary>
        internal static string OPEN_DIRECTORY {
            get {
                return ResourceManager.GetString("OPEN_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open in explorer ähnelt.
        /// </summary>
        internal static string OPEN_IN_EXPLORER {
            get {
                return ResourceManager.GetString("OPEN_IN_EXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opções ähnelt.
        /// </summary>
        internal static string OPTIONS {
            get {
                return ResourceManager.GetString("OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Options ähnelt.
        /// </summary>
        internal static string OPTIONS_TITLE {
            get {
                return ResourceManager.GetString("OPTIONS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page size ähnelt.
        /// </summary>
        internal static string PAGE_SIZE {
            get {
                return ResourceManager.GetString("PAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to patch your version to {0}? ähnelt.
        /// </summary>
        internal static string PATCH_VERSION {
            get {
                return ResourceManager.GetString("PATCH_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Patch version ähnelt.
        /// </summary>
        internal static string PATCH_VERSION_TITLE {
            get {
                return ResourceManager.GetString("PATCH_VERSION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ping ähnelt.
        /// </summary>
        internal static string PING {
            get {
                return ResourceManager.GetString("PING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player time out ähnelt.
        /// </summary>
        internal static string PLAYER_TIME_OUT {
            get {
                return ResourceManager.GetString("PLAYER_TIME_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jogadores ähnelt.
        /// </summary>
        internal static string PLAYERS {
            get {
                return ResourceManager.GetString("PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please type in an username. ähnelt.
        /// </summary>
        internal static string PLEASE_TYPE_IN_USERNAME {
            get {
                return ResourceManager.GetString("PLEASE_TYPE_IN_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugins ähnelt.
        /// </summary>
        internal static string PLUGINS {
            get {
                return ResourceManager.GetString("PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Porta ähnelt.
        /// </summary>
        internal static string PORT {
            get {
                return ResourceManager.GetString("PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Português ähnelt.
        /// </summary>
        internal static string PORTUGUESE {
            get {
                return ResourceManager.GetString("PORTUGUESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Português de Brasil ähnelt.
        /// </summary>
        internal static string PORTUGUESE_BRAZIL {
            get {
                return ResourceManager.GetString("PORTUGUESE_BRAZIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versão do Produto ähnelt.
        /// </summary>
        internal static string PRODUCT_VERSION {
            get {
                return ResourceManager.GetString("PRODUCT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable query ähnelt.
        /// </summary>
        internal static string QUERY {
            get {
                return ResourceManager.GetString("QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable RCON ähnelt.
        /// </summary>
        internal static string RCON {
            get {
                return ResourceManager.GetString("RCON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password de RCON ähnelt.
        /// </summary>
        internal static string RCON_PASSWORD {
            get {
                return ResourceManager.GetString("RCON_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Password RCON ähnelt.
        /// </summary>
        internal static string RCON_PASSWORD_TITLE {
            get {
                return ResourceManager.GetString("RCON_PASSWORD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Região ähnelt.
        /// </summary>
        internal static string REGION {
            get {
                return ResourceManager.GetString("REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Queres mesmo eliminar a API selecionada? ähnelt.
        /// </summary>
        internal static string REMOVE_API {
            get {
                return ResourceManager.GetString("REMOVE_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eliminar API selecionada ähnelt.
        /// </summary>
        internal static string REMOVE_API_TITLE {
            get {
                return ResourceManager.GetString("REMOVE_API_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eliminar API selecionada ähnelt.
        /// </summary>
        internal static string REMOVE_SELECTED_API {
            get {
                return ResourceManager.GetString("REMOVE_SELECTED_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Queres mesmo eliminar este servidor dos teus favoritos? ähnelt.
        /// </summary>
        internal static string REMOVE_SERVER_FROM_FAVOURITES {
            get {
                return ResourceManager.GetString("REMOVE_SERVER_FROM_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eliminar servidor dos favoritos ähnelt.
        /// </summary>
        internal static string REMOVE_SERVER_FROM_FAVOURITES_TITLE {
            get {
                return ResourceManager.GetString("REMOVE_SERVER_FROM_FAVOURITES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to revert the API list to default? ähnelt.
        /// </summary>
        internal static string REVERT_API_LIST {
            get {
                return ResourceManager.GetString("REVERT_API_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Revert API list ähnelt.
        /// </summary>
        internal static string REVERT_API_LIST_TITLE {
            get {
                return ResourceManager.GetString("REVERT_API_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        internal static string REVERT_CONFIG {
            get {
                return ResourceManager.GetString("REVERT_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Russian (Русский) ähnelt.
        /// </summary>
        internal static string RUSSIAN {
            get {
                return ResourceManager.GetString("RUSSIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Guardar ähnelt.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search on... ähnelt.
        /// </summary>
        internal static string SEARCH_ON {
            get {
                return ResourceManager.GetString("SEARCH_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bing ähnelt.
        /// </summary>
        internal static string SEARCH_ON_BING {
            get {
                return ResourceManager.GetString("SEARCH_ON_BING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DuckDuckGo ähnelt.
        /// </summary>
        internal static string SEARCH_ON_DUCK_DUCK_GO {
            get {
                return ResourceManager.GetString("SEARCH_ON_DUCK_DUCK_GO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Google ähnelt.
        /// </summary>
        internal static string SEARCH_ON_GOOGLE {
            get {
                return ResourceManager.GetString("SEARCH_ON_GOOGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yahoo ähnelt.
        /// </summary>
        internal static string SEARCH_ON_YAHOO {
            get {
                return ResourceManager.GetString("SEARCH_ON_YAHOO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yandex ähnelt.
        /// </summary>
        internal static string SEARCH_ON_YANDEX {
            get {
                return ResourceManager.GetString("SEARCH_ON_YANDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die YouTube ähnelt.
        /// </summary>
        internal static string SEARCH_ON_YOU_TUBE {
            get {
                return ResourceManager.GetString("SEARCH_ON_YOU_TUBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lista de Servidores: ähnelt.
        /// </summary>
        internal static string SELECT_API {
            get {
                return ResourceManager.GetString("SELECT_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Andreas Multiplayer - Select favourite list ähnelt.
        /// </summary>
        internal static string SELECT_FAVOURITE_LIST_TITLE {
            get {
                return ResourceManager.GetString("SELECT_FAVOURITE_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select favourites list ähnelt.
        /// </summary>
        internal static string SELECT_FAVOURITES_LIST {
            get {
                return ResourceManager.GetString("SELECT_FAVOURITES_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Língua: ähnelt.
        /// </summary>
        internal static string SELECT_LANGUAGE {
            get {
                return ResourceManager.GetString("SELECT_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lista de Servidores: ähnelt.
        /// </summary>
        internal static string SELECT_SERVER_LIST {
            get {
                return ResourceManager.GetString("SELECT_SERVER_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have selected {0} to be patched or manually installed.
        ///
        ///Do you really want to patch or manually install {0}?
        ///
        ///Press &quot;Yes&quot; to patch.
        ///Press &quot;No&quot; to install.
        ///Press &quot;Cancel&quot; to cancel this action. ähnelt.
        /// </summary>
        internal static string SELECT_VERSION {
            get {
                return ResourceManager.GetString("SELECT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Patch or manually install version ähnelt.
        /// </summary>
        internal static string SELECT_VERSION_TITLE {
            get {
                return ResourceManager.GetString("SELECT_VERSION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This server is already in your favourites. ähnelt.
        /// </summary>
        internal static string SERVER_ALREADY_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("SERVER_ALREADY_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This server is not in your favourites. ähnelt.
        /// </summary>
        internal static string SERVER_NOT_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("SERVER_NOT_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password: ähnelt.
        /// </summary>
        internal static string SERVER_PASSWORD {
            get {
                return ResourceManager.GetString("SERVER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server password field is empty.
        ///
        ///Do you want to continue? ähnelt.
        /// </summary>
        internal static string SERVER_PASSWORD_FIELD_IS_EMPTY {
            get {
                return ResourceManager.GetString("SERVER_PASSWORD_FIELD_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server password field is empty ähnelt.
        /// </summary>
        internal static string SERVER_PASSWORD_FIELD_IS_EMPTY_TITLE {
            get {
                return ResourceManager.GetString("SERVER_PASSWORD_FIELD_IS_EMPTY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Servidores ähnelt.
        /// </summary>
        internal static string SERVERS {
            get {
                return ResourceManager.GetString("SERVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filtros de servidores: ähnelt.
        /// </summary>
        internal static string SERVERS_FILTERS {
            get {
                return ResourceManager.GetString("SERVERS_FILTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configurações Adicionais ähnelt.
        /// </summary>
        internal static string SHOW_ADDITIONAL_CONFIGURATIONS {
            get {
                return ResourceManager.GetString("SHOW_ADDITIONAL_CONFIGURATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extended server information ähnelt.
        /// </summary>
        internal static string SHOW_EXTENDED_SERVER_INFORMATION {
            get {
                return ResourceManager.GetString("SHOW_EXTENDED_SERVER_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favourites ähnelt.
        /// </summary>
        internal static string SHOW_FAVOURITES {
            get {
                return ResourceManager.GetString("SHOW_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show gallery... ähnelt.
        /// </summary>
        internal static string SHOW_GALLERY {
            get {
                return ResourceManager.GetString("SHOW_GALLERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show in Google Maps ähnelt.
        /// </summary>
        internal static string SHOW_IN_GOOGLE_MAPS {
            get {
                return ResourceManager.GetString("SHOW_IN_GOOGLE_MAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show in OpenStreetMap ähnelt.
        /// </summary>
        internal static string SHOW_IN_OPEN_STREET_MAP {
            get {
                return ResourceManager.GetString("SHOW_IN_OPEN_STREET_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show last chatlog... ähnelt.
        /// </summary>
        internal static string SHOW_LAST_CHATLOG {
            get {
                return ResourceManager.GetString("SHOW_LAST_CHATLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favoritos do SA:MP ähnelt.
        /// </summary>
        internal static string SHOW_LEGACY_FAVOURITES {
            get {
                return ResourceManager.GetString("SHOW_LEGACY_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hostedlist ähnelt.
        /// </summary>
        internal static string SHOW_LEGACY_HOSTED_LIST {
            get {
                return ResourceManager.GetString("SHOW_LEGACY_HOSTED_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Masterlist ähnelt.
        /// </summary>
        internal static string SHOW_LEGACY_MASTER_LIST {
            get {
                return ResourceManager.GetString("SHOW_LEGACY_MASTER_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SACNR ähnelt.
        /// </summary>
        internal static string SHOW_SACNR_LIST {
            get {
                return ResourceManager.GetString("SHOW_SACNR_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lista do Southclaw ähnelt.
        /// </summary>
        internal static string SHOW_SOUTHCLAWS_LIST {
            get {
                return ResourceManager.GetString("SHOW_SOUTHCLAWS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sleep time ähnelt.
        /// </summary>
        internal static string SLEEP {
            get {
                return ResourceManager.GetString("SLEEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iníciar Servidor ähnelt.
        /// </summary>
        internal static string START_SERVER {
            get {
                return ResourceManager.GetString("START_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parar Servidor ähnelt.
        /// </summary>
        internal static string STOP_SERVER {
            get {
                return ResourceManager.GetString("STOP_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stream distance ähnelt.
        /// </summary>
        internal static string STREAM_DISTANCE {
            get {
                return ResourceManager.GetString("STREAM_DISTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stream rate ähnelt.
        /// </summary>
        internal static string STREAM_RATE {
            get {
                return ResourceManager.GetString("STREAM_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Não guardar Nickname ähnelt.
        /// </summary>
        internal static string TEMPORARY_USERNAME {
            get {
                return ResourceManager.GetString("TEMPORARY_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time zone ähnelt.
        /// </summary>
        internal static string TIME_ZONE {
            get {
                return ResourceManager.GetString("TIME_ZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timestamp ähnelt.
        /// </summary>
        internal static string TIMESTAMP {
            get {
                return ResourceManager.GetString("TIMESTAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nickname: ähnelt.
        /// </summary>
        internal static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versões ähnelt.
        /// </summary>
        internal static string VERSIONS {
            get {
                return ResourceManager.GetString("VERSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visit website ähnelt.
        /// </summary>
        internal static string VISIT_WEBSITE {
            get {
                return ResourceManager.GetString("VISIT_WEBSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to visit this website? ähnelt.
        /// </summary>
        internal static string VISIT_WEBSITE_MESSAGE {
            get {
                return ResourceManager.GetString("VISIT_WEBSITE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visit ähnelt.
        /// </summary>
        internal static string VISIT_WEBSITE_TITLE {
            get {
                return ResourceManager.GetString("VISIT_WEBSITE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weapon rate ähnelt.
        /// </summary>
        internal static string WEAPON_RATE {
            get {
                return ResourceManager.GetString("WEAPON_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Website URL ähnelt.
        /// </summary>
        internal static string WEBSITE_URL {
            get {
                return ResourceManager.GetString("WEBSITE_URL", resourceCulture);
            }
        }
    }
}
