//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPLauncherNET.Languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ru_RU() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAMPLauncherNET.Languages.ru-RU", typeof(ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        internal static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SAMPLauncher NET - это загрузчик для San Andreas Multiplayer.
        ///
        ///Это программное обеспечение бесплатно и лицензировано по лицензии GPLv3.
        ///
        ///Этот проект находится.
        /// </summary>
        internal static string ABOUT_DESCRIPTION {
            get {
                return ResourceManager.GetString("ABOUT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ограничения доступа.
        /// </summary>
        internal static string ACKNOWLEDGES_LIMIT {
            get {
                return ResourceManager.GetString("ACKNOWLEDGES_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить новый API.
        /// </summary>
        internal static string ADD_NEW_API {
            get {
                return ResourceManager.GetString("ADD_NEW_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить сервер в избранное.
        /// </summary>
        internal static string ADD_SERVER_TO_FAVOURITES {
            get {
                return ResourceManager.GetString("ADD_SERVER_TO_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уже в избранном.
        /// </summary>
        internal static string ALREADY_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("ALREADY_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видимость сервера.
        /// </summary>
        internal static string ANNOUNCE {
            get {
                return ResourceManager.GetString("ANNOUNCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на API.
        /// </summary>
        internal static string API {
            get {
                return ResourceManager.GetString("API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конечная точка API.
        /// </summary>
        internal static string API_ENDPOINT {
            get {
                return ResourceManager.GetString("API_ENDPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите действительную конечную точку для API.
        /// </summary>
        internal static string API_ENDPOINT_MISSING {
            get {
                return ResourceManager.GetString("API_ENDPOINT_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует конечная точка API.
        /// </summary>
        internal static string API_ENDPOINT_MISSING_TITLE {
            get {
                return ResourceManager.GetString("API_ENDPOINT_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя API.
        /// </summary>
        internal static string API_NAME {
            get {
                return ResourceManager.GetString("API_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста введите имя API..
        /// </summary>
        internal static string API_NAME_MISSING {
            get {
                return ResourceManager.GetString("API_NAME_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует имя API.
        /// </summary>
        internal static string API_NAME_MISSING_TITLE {
            get {
                return ResourceManager.GetString("API_NAME_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип API.
        /// </summary>
        internal static string API_TYPE {
            get {
                return ResourceManager.GetString("API_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста выберите тип API..
        /// </summary>
        internal static string API_TYPE_MISSING {
            get {
                return ResourceManager.GetString("API_TYPE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутсвуету тип API.
        /// </summary>
        internal static string API_TYPE_MISSING_TITLE {
            get {
                return ResourceManager.GetString("API_TYPE_MISSING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия сборки.
        /// </summary>
        internal static string ASSEMBLY_VERSION {
            get {
                return ResourceManager.GetString("ASSEMBLY_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выключить сообщения проигрываемого аудио потока.
        /// </summary>
        internal static string AUDIO_MESSAGE_OFF {
            get {
                return ResourceManager.GetString("AUDIO_MESSAGE_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выключить прокси для аудио потока.
        /// </summary>
        internal static string AUDIO_PROXY_OFF {
            get {
                return ResourceManager.GetString("AUDIO_PROXY_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прикрепить IP адрес.
        /// </summary>
        internal static string BIND {
            get {
                return ResourceManager.GetString("BIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить логирование чата.
        /// </summary>
        internal static string CHAT_LOGGING {
            get {
                return ResourceManager.GetString("CHAT_LOGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Город.
        /// </summary>
        internal static string CITY {
            get {
                return ResourceManager.GetString("CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть при запуске.
        /// </summary>
        internal static string CLOSE_WHEN_LAUNCHED {
            get {
                return ResourceManager.GetString("CLOSE_WHEN_LAUNCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключиться.
        /// </summary>
        internal static string CONNECT {
            get {
                return ResourceManager.GetString("CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключиться сейчас!.
        /// </summary>
        internal static string CONNECT_NOW {
            get {
                return ResourceManager.GetString("CONNECT_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на San Andreas Multiplayer - Подключиться.
        /// </summary>
        internal static string CONNECT_TITLE {
            get {
                return ResourceManager.GetString("CONNECT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключиться к адресу.
        /// </summary>
        internal static string CONNECT_TO_ADDRESS {
            get {
                return ResourceManager.GetString("CONNECT_TO_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на San Andreas Multiplayer - Подключиться к адресу.
        /// </summary>
        internal static string CONNECT_TO_ADDRESS_TITLE {
            get {
                return ResourceManager.GetString("CONNECT_TO_ADDRESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключиться к тестовому серверу.
        /// </summary>
        internal static string CONNECT_TO_TEST_SERVER {
            get {
                return ResourceManager.GetString("CONNECT_TO_TEST_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключиться с RCON.
        /// </summary>
        internal static string CONNECT_WITH_RCON {
            get {
                return ResourceManager.GetString("CONNECT_WITH_RCON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разрешить файлы cookie при подключении.
        /// </summary>
        internal static string CONNECTION_COOKIES {
            get {
                return ResourceManager.GetString("CONNECTION_COOKIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время установления соединения.
        /// </summary>
        internal static string CONNECTION_SEED_TIME {
            get {
                return ResourceManager.GetString("CONNECTION_SEED_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить логирование файлов cookie.
        /// </summary>
        internal static string COOKIE_LOGGING {
            get {
                return ResourceManager.GetString("COOKIE_LOGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страна.
        /// </summary>
        internal static string COUNTRY {
            get {
                return ResourceManager.GetString("COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логирование запросов к базе данных.
        /// </summary>
        internal static string DATABASE_LOG_QUERIES {
            get {
                return ResourceManager.GetString("DATABASE_LOG_QUERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить логирование базы данных.
        /// </summary>
        internal static string DATABASE_LOGGING {
            get {
                return ResourceManager.GetString("DATABASE_LOGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим отладки.
        /// </summary>
        internal static string DEBUG_MODE {
            get {
                return ResourceManager.GetString("DEBUG_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить выбранные изображения?.
        /// </summary>
        internal static string DELETE_SELECTED_IMAGES {
            get {
                return ResourceManager.GetString("DELETE_SELECTED_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить выбранные изображения.
        /// </summary>
        internal static string DELETE_SELECTED_IMAGES_TITLE {
            get {
                return ResourceManager.GetString("DELETE_SELECTED_IMAGES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструменты разработчика.
        /// </summary>
        internal static string DEVELOPER_TOOLS {
            get {
                return ResourceManager.GetString("DEVELOPER_TOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на San Andreas Multiplayer - Настройка инструментов разработчика.
        /// </summary>
        internal static string DEVELOPER_TOOLS_CONFIGURATION_TITLE {
            get {
                return ResourceManager.GetString("DEVELOPER_TOOLS_CONFIGURATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Директория разработки.
        /// </summary>
        internal static string DEVELOPMENT_DIRECTORY {
            get {
                return ResourceManager.GetString("DEVELOPMENT_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рендеринг TextDraw прямо на экран (медленно).
        /// </summary>
        internal static string DIRECT_MODE {
            get {
                return ResourceManager.GetString("DIRECT_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключить поворот головы.
        /// </summary>
        internal static string DISABLE_HEAD_MOVE {
            get {
                return ResourceManager.GetString("DISABLE_HEAD_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Голландский (Nederlands).
        /// </summary>
        internal static string DUTCH {
            get {
                return ResourceManager.GetString("DUTCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на San Andreas Multiplayer - Редактирование API.
        /// </summary>
        internal static string EDIT_API_TITLE {
            get {
                return ResourceManager.GetString("EDIT_API_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать выбранный API.
        /// </summary>
        internal static string EDIT_SELECTED_API {
            get {
                return ResourceManager.GetString("EDIT_SELECTED_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский (English).
        /// </summary>
        internal static string ENGLISH {
            get {
                return ResourceManager.GetString("ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на San Andreas Multiplayer - Расширенная информация о сервере.
        /// </summary>
        internal static string EXTENDED_SERVER_INFORMATION_TITLE {
            get {
                return ResourceManager.GetString("EXTENDED_SERVER_INFORMATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста выберите список избранных..
        /// </summary>
        internal static string FAVOURITE_LIST_NOT_SELECTED {
            get {
                return ResourceManager.GetString("FAVOURITE_LIST_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список избранных не выбран.
        /// </summary>
        internal static string FAVOURITE_LIST_NOT_SELECTED_TITLE {
            get {
                return ResourceManager.GetString("FAVOURITE_LIST_NOT_SELECTED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия файла.
        /// </summary>
        internal static string FILE_VERSION {
            get {
                return ResourceManager.GetString("FILE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр по имени сервера.
        /// </summary>
        internal static string FILTER_HOSTNAME {
            get {
                return ResourceManager.GetString("FILTER_HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр по IP и порту.
        /// </summary>
        internal static string FILTER_IP_AND_PORT {
            get {
                return ResourceManager.GetString("FILTER_IP_AND_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Языковой фильтр.
        /// </summary>
        internal static string FILTER_LANGUAGE {
            get {
                return ResourceManager.GetString("FILTER_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр по режиму.
        /// </summary>
        internal static string FILTER_MODE {
            get {
                return ResourceManager.GetString("FILTER_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filterscripts.
        /// </summary>
        internal static string FILTERSCRIPTS {
            get {
                return ResourceManager.GetString("FILTERSCRIPTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шрифт.
        /// </summary>
        internal static string FONT_FACE {
            get {
                return ResourceManager.GetString("FONT_FACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полужирный шрифт.
        /// </summary>
        internal static string FONT_WEIGHT {
            get {
                return ResourceManager.GetString("FONT_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ограничение FPS.
        /// </summary>
        internal static string FPS_LIMIT {
            get {
                return ResourceManager.GetString("FPS_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Галерея.
        /// </summary>
        internal static string GALLERY {
            get {
                return ResourceManager.GetString("GALLERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игровой режим.
        /// </summary>
        internal static string GAMEMODE {
            get {
                return ResourceManager.GetString("GAMEMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст игрового режима.
        /// </summary>
        internal static string GAMEMODE_TEXT {
            get {
                return ResourceManager.GetString("GAMEMODE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игровые режимы.
        /// </summary>
        internal static string GAMEMODES {
            get {
                return ResourceManager.GetString("GAMEMODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузинский (ქართული).
        /// </summary>
        internal static string GEORGIAN {
            get {
                return ResourceManager.GetString("GEORGIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Немецкий (Deutsch).
        /// </summary>
        internal static string GERMAN {
            get {
                return ResourceManager.GetString("GERMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GitHub проекта SAMPLauncherNET.
        /// </summary>
        internal static string GITHUB_PROJECT {
            get {
                return ResourceManager.GetString("GITHUB_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хост и порт.
        /// </summary>
        internal static string HOST_AND_PORT {
            get {
                return ResourceManager.GetString("HOST_AND_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название сервера.
        /// </summary>
        internal static string HOSTNAME {
            get {
                return ResourceManager.GetString("HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить IME (Input Method Editor - Редактор метода ввода).
        /// </summary>
        internal static string IME {
            get {
                return ResourceManager.GetString("IME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость обновления данных транспорта.
        /// </summary>
        internal static string IN_CAR_RATE {
            get {
                return ResourceManager.GetString("IN_CAR_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка ввода.
        /// </summary>
        internal static string INPUT_ERROR {
            get {
                return ResourceManager.GetString("INPUT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вводите фильтр здесь...
        /// </summary>
        internal static string INSERT_FILTER_HERE {
            get {
                return ResourceManager.GetString("INSERT_FILTER_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вводите RCON пароль здесь....
        /// </summary>
        internal static string INSERT_RCON_PASSWORD_HERE {
            get {
                return ResourceManager.GetString("INSERT_RCON_PASSWORD_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вводите пароль сервера здесь....
        /// </summary>
        internal static string INSERT_SERVER_PASSWORD_HERE {
            get {
                return ResourceManager.GetString("INSERT_SERVER_PASSWORD_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вводите имя игрока здесь....
        /// </summary>
        internal static string INSERT_USERNAME_HERE {
            get {
                return ResourceManager.GetString("INSERT_USERNAME_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IP и порт.
        /// </summary>
        internal static string IP_AND_PORT {
            get {
                return ResourceManager.GetString("IP_AND_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lag compensation mode.
        /// </summary>
        internal static string LAG_COMPENSATION_MODE {
            get {
                return ResourceManager.GetString("LAG_COMPENSATION_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LAN mode.
        /// </summary>
        internal static string LAN_MODE {
            get {
                return ResourceManager.GetString("LAN_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лог чата.
        /// </summary>
        internal static string LAST_CHATLOG {
            get {
                return ResourceManager.GetString("LAST_CHATLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Широта и долгота.
        /// </summary>
        internal static string LATITUDE_LONGITUDE {
            get {
                return ResourceManager.GetString("LATITUDE_LONGITUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим отладки.
        /// </summary>
        internal static string LAUNCH_DEBUG_MODE {
            get {
                return ResourceManager.GetString("LAUNCH_DEBUG_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим сюжета.
        /// </summary>
        internal static string LAUNCH_SINGLEPLAYER {
            get {
                return ResourceManager.GetString("LAUNCH_SINGLEPLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на San Andreas Multiplayer - Загрузчик.
        /// </summary>
        internal static string LAUNCHER_TITLE {
            get {
                return ResourceManager.GetString("LAUNCHER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лог запроов.
        /// </summary>
        internal static string LOG_QUERIES {
            get {
                return ResourceManager.GetString("LOG_QUERIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логируемый формат времени.
        /// </summary>
        internal static string LOG_TIME_FORMAT {
            get {
                return ResourceManager.GetString("LOG_TIME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название карты.
        /// </summary>
        internal static string MAP_NAME {
            get {
                return ResourceManager.GetString("MAP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальное число NPC.
        /// </summary>
        internal static string MAXIMAL_NPCS {
            get {
                return ResourceManager.GetString("MAXIMAL_NPCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальное число игроков.
        /// </summary>
        internal static string MAXIMAL_PLAYERS {
            get {
                return ResourceManager.GetString("MAXIMAL_PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message hole limit.
        /// </summary>
        internal static string MESSAGE_HOLE_LIMIT {
            get {
                return ResourceManager.GetString("MESSAGE_HOLE_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лимит сообщений.
        /// </summary>
        internal static string MESSAGES_LIMIT {
            get {
                return ResourceManager.GetString("MESSAGES_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код Metro.
        /// </summary>
        internal static string METRO_CODE {
            get {
                return ResourceManager.GetString("METRO_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Минимальное время подключения.
        /// </summary>
        internal static string MINIMUM_CONNECTION_TIME {
            get {
                return ResourceManager.GetString("MINIMUM_CONNECTION_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Многоядерность.
        /// </summary>
        internal static string MULTI_CORE {
            get {
                return ResourceManager.GetString("MULTI_CORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вам нужна помощь? Присоединяйтесь форумам SA:MP....
        /// </summary>
        internal static string NEED_HELP_FORUMS {
            get {
                return ResourceManager.GetString("NEED_HELP_FORUMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на San Andreas Multiplayer - Добавить новый API.
        /// </summary>
        internal static string NEW_API_TITLE {
            get {
                return ResourceManager.GetString("NEW_API_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдены логи чата....
        /// </summary>
        internal static string NO_CHATLOG_FOUND {
            get {
                return ResourceManager.GetString("NO_CHATLOG_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет ни одного списка избранных. Чтобы создать новый список избранного, выберите вкладку &quot;API и создайте новый список избранного или восстановите записи по умолчанию..
        /// </summary>
        internal static string NO_FAVOURITES {
            get {
                return ResourceManager.GetString("NO_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет избранных списков.
        /// </summary>
        internal static string NO_FAVOURITES_TITLE {
            get {
                return ResourceManager.GetString("NO_FAVOURITES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключить состояние в имени тэга.
        /// </summary>
        internal static string NO_NAMETAG_STATUS {
            get {
                return ResourceManager.GetString("NO_NAMETAG_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет подписи.
        /// </summary>
        internal static string NO_SIGN {
            get {
                return ResourceManager.GetString("NO_SIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не в избранных.
        /// </summary>
        internal static string NOT_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("NOT_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОК.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость обновления данных пешеходов.
        /// </summary>
        internal static string ON_FOOT_RATE {
            get {
                return ResourceManager.GetString("ON_FOOT_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть директорию.
        /// </summary>
        internal static string OPEN_DIRECTORY {
            get {
                return ResourceManager.GetString("OPEN_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть в проводнике.
        /// </summary>
        internal static string OPEN_IN_EXPLORER {
            get {
                return ResourceManager.GetString("OPEN_IN_EXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string OPTIONS {
            get {
                return ResourceManager.GetString("OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на San Andreas Multiplayer - Настройки.
        /// </summary>
        internal static string OPTIONS_TITLE {
            get {
                return ResourceManager.GetString("OPTIONS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество отображаемых строк в чате.
        /// </summary>
        internal static string PAGE_SIZE {
            get {
                return ResourceManager.GetString("PAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        internal static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пинг.
        /// </summary>
        internal static string PING {
            get {
                return ResourceManager.GetString("PING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тайм-аут игрока.
        /// </summary>
        internal static string PLAYER_TIME_OUT {
            get {
                return ResourceManager.GetString("PLAYER_TIME_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игроки.
        /// </summary>
        internal static string PLAYERS {
            get {
                return ResourceManager.GetString("PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя пользователя..
        /// </summary>
        internal static string PLEASE_TYPE_IN_USERNAME {
            get {
                return ResourceManager.GetString("PLEASE_TYPE_IN_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Плагины.
        /// </summary>
        internal static string PLUGINS {
            get {
                return ResourceManager.GetString("PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порт.
        /// </summary>
        internal static string PORT {
            get {
                return ResourceManager.GetString("PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия продукта.
        /// </summary>
        internal static string PRODUCT_VERSION {
            get {
                return ResourceManager.GetString("PRODUCT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить запросы.
        /// </summary>
        internal static string QUERY {
            get {
                return ResourceManager.GetString("QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить RCON.
        /// </summary>
        internal static string RCON {
            get {
                return ResourceManager.GetString("RCON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RCON пароль.
        /// </summary>
        internal static string RCON_PASSWORD {
            get {
                return ResourceManager.GetString("RCON_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на San Andreas Multiplayer - RCON пароль.
        /// </summary>
        internal static string RCON_PASSWORD_TITLE {
            get {
                return ResourceManager.GetString("RCON_PASSWORD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регион.
        /// </summary>
        internal static string REGION {
            get {
                return ResourceManager.GetString("REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить выбранный API?.
        /// </summary>
        internal static string REMOVE_API {
            get {
                return ResourceManager.GetString("REMOVE_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление выбранного API.
        /// </summary>
        internal static string REMOVE_API_TITLE {
            get {
                return ResourceManager.GetString("REMOVE_API_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить выбранный API.
        /// </summary>
        internal static string REMOVE_SELECTED_API {
            get {
                return ResourceManager.GetString("REMOVE_SELECTED_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить этот сервер из вашего списка избранных?.
        /// </summary>
        internal static string REMOVE_SERVER_FROM_FAVOURITES {
            get {
                return ResourceManager.GetString("REMOVE_SERVER_FROM_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление сервера из списка избранных.
        /// </summary>
        internal static string REMOVE_SERVER_FROM_FAVOURITES_TITLE {
            get {
                return ResourceManager.GetString("REMOVE_SERVER_FROM_FAVOURITES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите восстановить список API по умолчанию?.
        /// </summary>
        internal static string REVERT_API_LIST {
            get {
                return ResourceManager.GetString("REVERT_API_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить список API.
        /// </summary>
        internal static string REVERT_API_LIST_TITLE {
            get {
                return ResourceManager.GetString("REVERT_API_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить конфигурацию.
        /// </summary>
        internal static string REVERT_CONFIG {
            get {
                return ResourceManager.GetString("REVERT_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        internal static string RUSSIAN {
            get {
                return ResourceManager.GetString("RUSSIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохраненные позиции.
        /// </summary>
        internal static string SAVED_POSITIONS {
            get {
                return ResourceManager.GetString("SAVED_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Искать в....
        /// </summary>
        internal static string SEARCH_ON {
            get {
                return ResourceManager.GetString("SEARCH_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bing.
        /// </summary>
        internal static string SEARCH_ON_BING {
            get {
                return ResourceManager.GetString("SEARCH_ON_BING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DuckDuckGo.
        /// </summary>
        internal static string SEARCH_ON_DUCK_DUCK_GO {
            get {
                return ResourceManager.GetString("SEARCH_ON_DUCK_DUCK_GO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Google.
        /// </summary>
        internal static string SEARCH_ON_GOOGLE {
            get {
                return ResourceManager.GetString("SEARCH_ON_GOOGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yahoo.
        /// </summary>
        internal static string SEARCH_ON_YAHOO {
            get {
                return ResourceManager.GetString("SEARCH_ON_YAHOO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yandex.
        /// </summary>
        internal static string SEARCH_ON_YANDEX {
            get {
                return ResourceManager.GetString("SEARCH_ON_YANDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на YouTube.
        /// </summary>
        internal static string SEARCH_ON_YOU_TUBE {
            get {
                return ResourceManager.GetString("SEARCH_ON_YOU_TUBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Списки серверов.
        /// </summary>
        internal static string SELECT_API {
            get {
                return ResourceManager.GetString("SELECT_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на San Andreas Multiplayer - Выбор списка избранных.
        /// </summary>
        internal static string SELECT_FAVOURITE_LIST_TITLE {
            get {
                return ResourceManager.GetString("SELECT_FAVOURITE_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите список избранных.
        /// </summary>
        internal static string SELECT_FAVOURITES_LIST {
            get {
                return ResourceManager.GetString("SELECT_FAVOURITES_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор языка (Select language).
        /// </summary>
        internal static string SELECT_LANGUAGE {
            get {
                return ResourceManager.GetString("SELECT_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор списка серверов.
        /// </summary>
        internal static string SELECT_SERVER_LIST {
            get {
                return ResourceManager.GetString("SELECT_SERVER_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот сервер уже находится в избранных..
        /// </summary>
        internal static string SERVER_ALREADY_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("SERVER_ALREADY_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот сервер не находится в избранных..
        /// </summary>
        internal static string SERVER_NOT_IN_FAVOURITES {
            get {
                return ResourceManager.GetString("SERVER_NOT_IN_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль сервера.
        /// </summary>
        internal static string SERVER_PASSWORD {
            get {
                return ResourceManager.GetString("SERVER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пустое поле пароля сервера.\r\n\r\nВы хотите продолжить?.
        /// </summary>
        internal static string SERVER_PASSWORD_FIELD_IS_EMPTY {
            get {
                return ResourceManager.GetString("SERVER_PASSWORD_FIELD_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пустое поле пароля сервера.
        /// </summary>
        internal static string SERVER_PASSWORD_FIELD_IS_EMPTY_TITLE {
            get {
                return ResourceManager.GetString("SERVER_PASSWORD_FIELD_IS_EMPTY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервера.
        /// </summary>
        internal static string SERVERS {
            get {
                return ResourceManager.GetString("SERVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр списка серверов.
        /// </summary>
        internal static string SERVERS_FILTER {
            get {
                return ResourceManager.GetString("SERVERS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать дополнительные настройки.
        /// </summary>
        internal static string SHOW_ADDITIONAL_CONFIGURATIONS {
            get {
                return ResourceManager.GetString("SHOW_ADDITIONAL_CONFIGURATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расширенная информация о сервере.
        /// </summary>
        internal static string SHOW_EXTENDED_SERVER_INFORMATION {
            get {
                return ResourceManager.GetString("SHOW_EXTENDED_SERVER_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Избранные.
        /// </summary>
        internal static string SHOW_FAVOURITES {
            get {
                return ResourceManager.GetString("SHOW_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать галерею....
        /// </summary>
        internal static string SHOW_GALLERY {
            get {
                return ResourceManager.GetString("SHOW_GALLERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать в Google Maps.
        /// </summary>
        internal static string SHOW_IN_GOOGLE_MAPS {
            get {
                return ResourceManager.GetString("SHOW_IN_GOOGLE_MAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать в OpenStreetMap.
        /// </summary>
        internal static string SHOW_IN_OPEN_STREET_MAP {
            get {
                return ResourceManager.GetString("SHOW_IN_OPEN_STREET_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать последний лог чата....
        /// </summary>
        internal static string SHOW_LAST_CHATLOG {
            get {
                return ResourceManager.GetString("SHOW_LAST_CHATLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оригинальный список.
        /// </summary>
        internal static string SHOW_LEGACY_FAVOURITES {
            get {
                return ResourceManager.GetString("SHOW_LEGACY_FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список Hosted.
        /// </summary>
        internal static string SHOW_LEGACY_HOSTED_LIST {
            get {
                return ResourceManager.GetString("SHOW_LEGACY_HOSTED_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список Master.
        /// </summary>
        internal static string SHOW_LEGACY_MASTER_LIST {
            get {
                return ResourceManager.GetString("SHOW_LEGACY_MASTER_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время сна.
        /// </summary>
        internal static string SLEEP {
            get {
                return ResourceManager.GetString("SLEEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запустить сервер.
        /// </summary>
        internal static string START_SERVER {
            get {
                return ResourceManager.GetString("START_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановить сервер.
        /// </summary>
        internal static string STOP_SERVER {
            get {
                return ResourceManager.GetString("STOP_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дистанция области видимости.
        /// </summary>
        internal static string STREAM_DISTANCE {
            get {
                return ResourceManager.GetString("STREAM_DISTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость обновления области видимости.
        /// </summary>
        internal static string STREAM_RATE {
            get {
                return ResourceManager.GetString("STREAM_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не сохранять имя пользователя.
        /// </summary>
        internal static string TEMPORARY_USERNAME {
            get {
                return ResourceManager.GetString("TEMPORARY_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Временная зона.
        /// </summary>
        internal static string TIME_ZONE {
            get {
                return ResourceManager.GetString("TIME_ZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображать время сообщений в чате.
        /// </summary>
        internal static string TIMESTAMP {
            get {
                return ResourceManager.GetString("TIMESTAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя.
        /// </summary>
        internal static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посетить сайт.
        /// </summary>
        internal static string VISIT_WEBSITE {
            get {
                return ResourceManager.GetString("VISIT_WEBSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите посетить этот сайт?.
        /// </summary>
        internal static string VISIT_WEBSITE_MESSAGE {
            get {
                return ResourceManager.GetString("VISIT_WEBSITE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посетить.
        /// </summary>
        internal static string VISIT_WEBSITE_TITLE {
            get {
                return ResourceManager.GetString("VISIT_WEBSITE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость обновления данных об оружии.
        /// </summary>
        internal static string WEAPON_RATE {
            get {
                return ResourceManager.GetString("WEAPON_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес сайта.
        /// </summary>
        internal static string WEBSITE_URL {
            get {
                return ResourceManager.GetString("WEBSITE_URL", resourceCulture);
            }
        }
    }
}
